LPS-114982
liferay-tango/liferay-portal pull request #1261
Opened 2021-06-07 17:23 UTC by RitaSilveira

2021-06-07 17:25 UTC, RitaSilveira commented
@CarlosBrichete

2021-06-07 17:28 UTC, RitaSilveira commented
https://issues.liferay.com/browse/LPS-133339 , cc: @CarlosBrichete

2021-06-08 08:04 UTC, CarlosBrichete requested changes

2021-06-08 08:04 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +
Use the JSON macro to add the new site. See: https://issues.liferay.com/browse/LPS-130691

2021-06-08 08:04 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +
Use the JSON macro to add the new paga in the Site. See: https://issues.liferay.com/browse/LPS-130691

2021-06-08 08:04 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +
Why is this MessageboardsThread needed?

2021-06-08 08:04 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +
Use JSON macro to add users. See: https://issues.liferay.com/browse/LPS-130691

2021-06-08 08:04 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +
Why you do the check here? Isn't it supposed that you have to check it in the Site and Asset Library's modal within the Content Dashboard?

2021-06-08 08:04 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +
Please add tasks to divide the test and make it more readable. See: https://issues.liferay.com/browse/LPS-130691

2021-06-08 08:06 UTC, CarlosBrichete commented
Hey @RitaSilveira , add a description to the PR indicating the JIRA tickets affected and the motivation for this PR.

2021-06-10 07:13 UTC, merged