LPS-116987
liferay-tango/liferay-portal pull request #1374
Opened 2021-07-07 01:42 UTC by RitaSilveira

2021-07-07 01:55 UTC, RitaSilveira commented
https://issues.liferay.com/browse/LPS-134749, cc: @CarlosBrichete

2021-07-07 07:32 UTC, CarlosBrichete requested changes

2021-07-07 07:32 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		}
I think all these Click lines should be in a macro, like saveAsDraft(); or something like that

2021-07-07 07:32 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +
I think all these Click lines should be in a macro, like checkLanguage(); or something like that

2021-07-08 07:50 UTC, RitaSilveira commented
fixed

2021-07-08 08:03 UTC, CarlosBrichete commented
ci:test:sf

2021-07-08 08:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/45/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-source-format/builds/45/jenkins-report.html">here</a>.</b></p>

2021-07-08 08:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3ff9d993bd4f832b06fd1b780db0de552c9ceee1">3ff9d993bd4f832b06fd1b780db0de552c9ceee1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RitaSilveira/liferay-portal/tree/LPS-116987">LPS-116987</a><br/>Branch GIT ID: <a href="https://github.com/RitaSilveira/liferay-portal/commit/84a4e5e545e863f0cd03b05127a3007e60a39421">84a4e5e545e863f0cd03b05127a3007e60a39421</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/45/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/45/jenkins-report.html">here</a>.</h5></details></html>

2021-07-08 08:13 UTC, CarlosBrichete commented
ci:test:tango

2021-07-08 08:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>tango</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/47/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/47/jenkins-report.html">here</a>.</b></p>

2021-07-08 10:20 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:tango - 4 out of 8 jobs passed in 1 hour 58 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3ff9d993bd4f832b06fd1b780db0de552c9ceee1">3ff9d993bd4f832b06fd1b780db0de552c9ceee1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3ff9d993bd4f832b06fd1b780db0de552c9ceee1">3ff9d993bd4f832b06fd1b780db0de552c9ceee1</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2087">Acceptance Upstream DXP (master) #2087</a></p><details><summary><strong>ci:test:tango - 4 out of 8 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/47/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467434/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/229/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/477016/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/477015/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467432/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467433/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467431/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/47/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/229/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/229//consoleText">AXIS_VARIABLE=0,label_exp=!master #229</a><pre><code>     [exec]  ---&gt; 0074d24d84a5
     [exec] Step 14/16 : ENV LABEL_BUILD_DATE=${LABEL_BUILD_DATE}
     [exec]  ---&gt; Running in 88d64fabbbbc
     [exec] Removing intermediate container 88d64fabbbbc
     [exec]  ---&gt; e502aca38e5e
     [exec] Step 15/16 : ENV LABEL_VCS_REF=${LABEL_VCS_REF}
     [exec]  ---&gt; Running in b603bcdfc3d9
     [exec] Removing intermediate container b603bcdfc3d9
     [exec]  ---&gt; be0060b73d5f
     [exec] Step 16/16 : COPY --from=builder /builder/application .
     [exec]  ---&gt; 9a3334a2356b
     [exec] 
     [exec] Successfully built 9a3334a2356b
     [exec] Successfully tagged com-liferay-osb-asah-private_osbasahbackend:latest
     [exec] /bin/bash: ./gradlew: No such file or directory
[stopwatch] [run.batch.test.action: 9:21.049 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1626: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1630: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:14089: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-analytics-cloud.xml:211: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-analytics-cloud.xml:142: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:521: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:640: exec returned: 127
      [get] Getting: http://test-1-27/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/229//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210708022530444.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210708022530444.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null793776753.properties</code></pre></div></li><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/229//consoleText">AXIS_VARIABLE=1,label_exp=!master #229</a><pre><code>     [exec]  ---&gt; 2576726b0cd1
     [exec] Step 14/16 : ENV LABEL_BUILD_DATE=${LABEL_BUILD_DATE}
     [exec]  ---&gt; Running in 5bf16de7e22f
     [exec] Removing intermediate container 5bf16de7e22f
     [exec]  ---&gt; 6e17793d2ad9
     [exec] Step 15/16 : ENV LABEL_VCS_REF=${LABEL_VCS_REF}
     [exec]  ---&gt; Running in 74e62d9192cc
     [exec] Removing intermediate container 74e62d9192cc
     [exec]  ---&gt; f62900efd973
     [exec] Step 16/16 : COPY --from=builder /builder/application .
     [exec]  ---&gt; ce692bdb5f44
     [exec] 
     [exec] Successfully built ce692bdb5f44
     [exec] Successfully tagged com-liferay-osb-asah-private_osbasahbackend:latest
     [exec] /bin/bash: ./gradlew: No such file or directory
[stopwatch] [run.batch.test.action: 9:17.368 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1626: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1630: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:14089: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-analytics-cloud.xml:211: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-analytics-cloud.xml:142: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:521: The following error oc [...]

2021-07-08 10:21 UTC, CarlosBrichete commented
ci:forward

2021-07-08 10:21 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-07-08 10:21 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-07-08 10:23 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/forward-pullrequest/378//consoleFull)

2021-07-12 12:21 UTC, RitaSilveira commented
fixed

2021-07-12 12:40 UTC, CarlosBrichete commented
ci:forward

2021-07-12 12:40 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-07-12 12:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-source-format/5671/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-portal-source-format/builds/5671/jenkins-report.html">here</a>.</b></p>

2021-07-12 12:43 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 1 minute</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f04ab1731b97a88ca360afa8883efc514a1f2e4e">f04ab1731b97a88ca360afa8883efc514a1f2e4e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RitaSilveira/liferay-portal/tree/LPS-116987">LPS-116987</a><br/>Branch GIT ID: <a href="https://github.com/RitaSilveira/liferay-portal/commit/9f650b3ca025fdc4fc57993e1c07380547b8114d">9f650b3ca025fdc4fc57993e1c07380547b8114d</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/5671/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/5671/jenkins-report.html">here</a>.</h5><div><p>Please fix <strong>rebase errors</strong> on <strong><a href="https://github.com/RitaSilveira/liferay-portal/tree/LPS-116987">RitaSilveira/LPS-116987</a></strong><pre><code>Target exception: java.lang.RuntimeException: Unable to rebase RitaSilveira-1374-LPS-116987 to master
error: Failed to merge in the changes.</code></pre></p></div></details></html>

2021-07-12 13:34 UTC, closed without merging