LPS-117341
liferay-tango/liferay-portal pull request #1424
Opened 2021-07-19 07:11 UTC by RitaSilveira

2021-07-19 07:11 UTC, liferay-continuous-integration commented
Please only forward critical changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing 7.4 DXP EP3 & CE GA3 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-07-19 07:15 UTC, RitaSilveira commented
https://issues.liferay.com/browse/LPS-134022, cc: @CarlosBrichete

2021-07-19 07:41 UTC, CarlosBrichete requested changes

2021-07-19 07:41 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +
We don't use Pause anymore, please use Wait methods instead

2021-07-19 07:41 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		}
Why do you create a new method when you can use JSON macro to create categories?

2021-07-19 07:41 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		}
This is not needed, you can use JSON macro to create a web content with several categories.

2021-07-19 20:16 UTC, RitaSilveira commented
fixed

2021-07-20 10:08 UTC, CarlosBrichete commented
ci:test:sf

2021-07-20 10:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2839/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/2839/jenkins-report.html">here</a>.</b></p>

2021-07-20 10:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0ea7cfcee785f4a642b944b15937de099275b013">0ea7cfcee785f4a642b944b15937de099275b013</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RitaSilveira/liferay-portal/tree/LPS-117341">LPS-117341</a><br/>Branch GIT ID: <a href="https://github.com/RitaSilveira/liferay-portal/commit/da0651f03a3fd45a4fca43367a1fdc4a620fc9a7">da0651f03a3fd45a4fca43367a1fdc4a620fc9a7</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2839/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2839/jenkins-report.html">here</a>.</h5><div><p>POSHI Validation Failure<pre><code>     [exec] 1 errors in Poshi script syntax
     [exec] 
     [exec] Unmatched opening boundary at:
     [exec] 
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase:2
     [exec] definition \{
     [exec]            ^
     [exec] 
     [exec] 
     [exec] 	at com.liferay.poshi.core.PoshiContext.readFiles(PoshiContext.java:492)
     [exec] 	at com.liferay.poshi.core.PoshiValidation.main(PoshiValidation.java:54)
     [exec] 
     [exec] &gt; Task :validatePoshi FAILED</code></pre></p></div></details></html>

2021-07-20 10:12 UTC, CarlosBrichete commented
@RitaSilveira SF failed :(

2021-07-20 10:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2839/">test-portal-source-format#2839</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2839/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1424">liferay-tango#1424</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548346473">[master] ci:test:sf - RitaSilveira &gt; liferay-tango - PR#1424 - 2021-07-20[03:08:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/8648/">publish-testray-report#8648</a><br/></div></div>

2021-07-20 13:15 UTC, RitaSilveira commented
fixed

2021-07-20 13:27 UTC, CarlosBrichete commented
ci:test:sf

2021-07-20 13:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/382/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-source-format/builds/382/jenkins-report.html">here</a>.</b></p>

2021-07-20 13:30 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0ea7cfcee785f4a642b944b15937de099275b013">0ea7cfcee785f4a642b944b15937de099275b013</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RitaSilveira/liferay-portal/tree/LPS-117341">LPS-117341</a><br/>Branch GIT ID: <a href="https://github.com/RitaSilveira/liferay-portal/commit/cf46b2320305928c8ddf358c6d2977a9f5bac84c">cf46b2320305928c8ddf358c6d2977a9f5bac84c</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/382/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/382/jenkins-report.html">here</a>.</h5><div><p>POSHI Validation Failure<pre><code>     [exec] 1 errors in Poshi script syntax
     [exec] 
     [exec] Unmatched opening boundary at:
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase:2
     [exec] definition \{
     [exec]            ^
     [exec] 
     [exec] 
     [exec] Exception in thread "main" java.lang.Exception
     [exec] 	at com.liferay.poshi.core.script.PoshiScriptParserException.throwExceptions(PoshiScriptParserException.java:51)
     [exec] 	at com.liferay.poshi.core.PoshiContext.readFiles(PoshiContext.java:565)
     [exec] 	at com.liferay.poshi.core.PoshiContext.readFiles(PoshiContext.java:492)
     [exec] 	at com.liferay.poshi.core.PoshiValidation.main(PoshiValidation.java:54)
     [exec] 
     [exec] &gt; Task :validatePoshi FAILED</code></pre></p></div></details></html>

2021-07-20 13:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/382/">test-portal-source-format#382</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/382/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1424">liferay-tango#1424</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548409516">[master] ci:test:sf - RitaSilveira &gt; liferay-tango - PR#1424 - 2021-07-20[06:27:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/472/">publish-testray-report#472</a><br/></div></div>

2021-07-20 13:48 UTC, RitaSilveira commented
fixed

2021-07-20 14:38 UTC, CarlosBrichete commented
ci:test:sf

2021-07-20 14:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/384/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-source-format/builds/384/jenkins-report.html">here</a>.</b></p>

2021-07-20 14:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0ea7cfcee785f4a642b944b15937de099275b013">0ea7cfcee785f4a642b944b15937de099275b013</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RitaSilveira/liferay-portal/tree/LPS-117341">LPS-117341</a><br/>Branch GIT ID: <a href="https://github.com/RitaSilveira/liferay-portal/commit/c1bbe4e9069c00b9e89ec975eb16c42d5d4ff27f">c1bbe4e9069c00b9e89ec975eb16c42d5d4ff27f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/384/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/384/jenkins-report.html">here</a>.</h5></details></html>

2021-07-20 14:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/384/">test-portal-source-format#384</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/384/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1424">liferay-tango#1424</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548418481">[master] ci:test:sf - RitaSilveira &gt; liferay-tango - PR#1424 - 2021-07-20[07:38:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/479/">publish-testray-report#479</a><br/></div></div>

2021-07-20 15:38 UTC, CarlosBrichete commented
ci:test:tango

2021-07-20 15:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>tango</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/403/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/403/jenkins-report.html">here</a>.</b></p>

2021-07-20 17:22 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:tango - 4 out of 8 jobs passed in 1 hour 44 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0ea7cfcee785f4a642b944b15937de099275b013">0ea7cfcee785f4a642b944b15937de099275b013</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0ea7cfcee785f4a642b944b15937de099275b013">0ea7cfcee785f4a642b944b15937de099275b013</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2123">Acceptance Upstream DXP (master) #2123</a></p><details><summary><strong>ci:test:tango - 4 out of 8 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/403/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/232102/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/474035/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9000/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/421/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/232101/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/419/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/420/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/403/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/232102/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>22 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/232102//consoleText">AXIS_VARIABLE=3,label_exp=!master #232102</a><pre><code>clean-up-web-xml:
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.43/webapps/ROOT/WEB-INF
[stopwatch] [run.tomcat: 18:30.318 sec]
[stopwatch] [run.selenium.tomcat: 19:04.737 sec]
     [exec] 55c41a2a3be5
     [exec] 55c41a2a3be5
     [exec] Result: 1
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/docker_stop.sh
[stopwatch] [run.batch.test.action: 19:32.042 sec]
     [echo] 
      [get] Getting: http://test-1-18/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/232102//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210720120614465.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210720120614465.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null377777601.properties</code></pre></div></li><li><div><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=18,label_exp=!master/232102//consoleText">AXIS_VARIABLE=18,label_exp=!master #232102</a><ol><li><div><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=18,label_exp=!master/232102//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ContentDashboardAuditGraph_KeepInfomationOfDeleteVocabularyInSegment_">LocalFile.ContentDashboardAuditGraph#KeepInfomationOfDeleteVocabularyInSegment</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/403/functional-tomcat90-mysql57-jdk8/0/18/LocalFile.ContentDashboardAuditGraph_KeepInfomationOfDeleteVocabularyInSegment/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/403/functional-tomcat90-mysql57-jdk8/0/18/LocalFile.ContentDashboardAuditGraph_KeepInfomationOfDeleteVocabularyInSegment/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/403/functional-tomcat90-mysql57-jdk8/0/18/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=23,label_exp=!master/232102//consoleText">AXIS_VARIABLE=23,label_exp=!master #232102</a><ol><li><div><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=23,label_exp=!master/232102//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ExperienceCreateExperience_AddNewExperienceSessionLanguageSegment_">LocalFile.ExperienceCreateExperience#AddNewExperienceSessionLanguageSegment</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/403/functional-tomcat90-mysql57-jdk8/0/23/LocalFile.ExperienceCreateExperience_AddNewExperienceSessionLanguageSegment/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/403/functional-tomcat90-mysql57-jdk8/0/23/LocalFile.ExperienceCreateExperience_AddNewExperienceSessionLanguageSegment/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/403/functional-tomcat90-mysql57-jdk8/0/23/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9000/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></h5><div><h6>Job Results:</h6><p>3 Tests Passed.<br/>5 Tests Failed.</p></div><ol><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/9000//consoleText">AXIS_VARIABLE=0,label_exp=!master #9000</a><ol><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/9000//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateABTest_CreateABTestByBounceRate_">LocalFile.CreateABTest#CreateABTestByBounceRate</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/403/functional-tomcat90-mysql57-jdk8/3/0/LocalFile.CreateABTest_CreateABTestByBounceRate/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-p [...]

2021-07-20 17:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/403/">test-portal-acceptance-pullrequest(master)#403</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/403/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>tango<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1424">liferay-tango#1424</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548475850">[master] ci:test:tango - RitaSilveira &gt; liferay-tango - PR#1424 - 2021-07-20[08:38:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/494/">publish-testray-report#494</a><br/></div></div>

2021-07-20 20:09 UTC, CarlosBrichete commented
ci:forward

2021-07-20 20:09 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-07-20 20:09 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-07-20 20:11 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-28.liferay.com/job/forward-pullrequest/7//consoleFull)

2021-07-20 20:11 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/104588
[Console](https://test-1-28.liferay.com/job/forward-pullrequest/7//consoleFull)

2021-07-20 20:11 UTC, closed without merging