LPS-113832
liferay-tango/liferay-portal pull request #1437
Opened 2021-07-21 02:36 UTC by RitaSilveira

2021-07-21 02:36 UTC, liferay-continuous-integration commented
Please only forward critical changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing 7.4 DXP EP3 & CE GA3 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-07-21 02:41 UTC, RitaSilveira commented
https://issues.liferay.com/browse/LPS-135988, cc: @CarlosBrichete

2021-07-21 08:07 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +
can you use the JSON macro to create the user instead of the CP method?

2021-07-21 08:08 UTC, CarlosBrichete commented
Hi @RitaSilveira ! I left you a comment, please review it :)

2021-07-22 03:53 UTC, RitaSilveira commented
fixed

2021-07-23 07:29 UTC, CarlosBrichete requested changes

2021-07-23 07:29 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +
Since you are creating your user using JSON macro, there's no need to go to the Users and Organization portlet anymore

2021-07-23 07:29 UTC, CarlosBrichete commented
@RitaSilveira fix this little thing and we can go :)

2021-07-23 23:42 UTC, RitaSilveira commented
fixed

2021-08-03 10:59 UTC, CarlosBrichete commented
ci:test:tango

2021-08-03 10:59 UTC, CarlosBrichete commented
ci:test:sf

2021-08-03 11:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3169/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/3169/jenkins-report.html">here</a>.</b></p>

2021-08-03 11:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d75a749f503bcaa193680fefda7da441807476a3">d75a749f503bcaa193680fefda7da441807476a3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RitaSilveira/liferay-portal/tree/LPS-113832">LPS-113832</a><br/>Branch GIT ID: <a href="https://github.com/RitaSilveira/liferay-portal/commit/f9503576cce65dde68bc722ab0413648afb7de62">f9503576cce65dde68bc722ab0413648afb7de62</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3169/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3169/jenkins-report.html">here</a>.</h5></details></html>

2021-08-03 11:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3169/">test-portal-source-format#3169</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3169/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1437">liferay-tango#1437</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551187247">[master] ci:test:sf - RitaSilveira &gt; liferay-tango - PR#1437 - 2021-08-03[03:59:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9643/">publish-testray-report#9643</a><br/></div></div>

2021-08-03 11:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>tango</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/56/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/56/jenkins-report.html">here</a>.</b></p>

2021-08-03 13:33 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:tango - 4 out of 8 jobs passed in 2 hours 33 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2172">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1307401_56</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d75a749f503bcaa193680fefda7da441807476a3">d75a749f503bcaa193680fefda7da441807476a3</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/61815a0f9c81d83f62c4d570f193385bef737ef3">61815a0f9c81d83f62c4d570f193385bef737ef3</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2171">Acceptance Upstream DXP (master) #2171</a></p><details><summary><strong>ci:test:tango - 4 out of 8 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/56/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/936/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/918/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9085/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6729/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/787/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3487/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/786/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/56/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9085/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/9085//consoleText">AXIS_VARIABLE=2,label_exp=!master #9085</a><pre><code>     [exec] * What went wrong:
     [exec] Execution failed for task ':dxp:apps:osb:osb-faro:osb-faro-theme:gulpBuild'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/com-liferay-osb-faro-private/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org
     [exec] 
     [exec] BUILD FAILED in 4s
     [exec] 
     [exec] &gt; Task :dxp:apps:osb:osb-faro:osb-faro-theme:gulpBuild FAILED
     [exec] [05:53:00] Using gulpfile /opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/gulpfile.js
     [exec] [05:53:00] Starting 'build'...
     [exec] [05:53:00] Starting 'build:clean'...
     [exec] [05:53:00] Finished 'build:clean' after 129 ms
     [exec] [05:53:00] Starting 'build:base'...
     [exec] [05:53:01] Finished 'build:base' after 620 ms
     [exec] [05:53:01] Starting 'build:src'...
     [exec] [05:53:01] Finished 'build:src' after 7.15 ms
     [exec] [05:53:01] Starting 'build:web-inf'...
     [exec] [05:53:01] Finished 'build:web-inf' after 1.49 ms
     [exec] [05:53:01] Starting 'build:liferay-look-and-feel'...
     [exec] [05:53:01] Finished 'build:liferay-look-and-feel' after 11 ms
     [exec] [05:53:01] Starting 'build:hook'...
     [exec] [05:53:01] Finished 'build:hook' after 4.08 ms
     [exec] [05:53:01] Starting 'build:themelets'...
     [exec] [05:53:01] Starting 'build:themelet-src'...
     [exec] [05:53:01] Finished 'build:themelet-src' after 612 ??s
     [exec] [05:53:01] Starting 'build:themelet-css-inject'...
     [exec] [05:53:01] Starting 'build:themelet-js-inject'...
     [exec] [05:53:01] &#27;[35mgulp-inject&#27;[39m Nothing to inject into &#27;[35m_custom.scss&#27;[39m.
     [exec] [05:53:01] &#27;[35mgulp-inject&#27;[39m Nothing to inject into &#27;[35mportal_normal.ftl&#27;[39m.
     [exec] [05:53:01] Finished 'build:themelet-css-inject' after 27 ms
     [exec] [05:53:01] Finished 'build:themelet-js-inject' after 7.44 ms
     [exec] [05:53:01] Finished 'build:themelets' after 28 ms
     [exec] [05:53:01] Starting 'build:rename-css-dir'...
     [exec] [05:53:01] Finished 'build:rename-css-dir' after 136 ??s
     [exec] [05:53:01] Starting 'build:compile-css'...
     [exec] [05:53:01] Starting 'build:compile-lib-sass'...</code></pre></div></li><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/9085//consoleText">AXIS_VARIABLE=0,label_exp=!master #9085</a><ol><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/9085//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateABTest_CreateABTestByBounceRate_">LocalFile.CreateABTest#CreateABTestByBounceRate</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/56/functional-tomcat90-mysql57-jdk8/3/0/LocalFile.CreateABTest_CreateABTestByBounceRate/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/56/functional-tomcat90-mysql57-jdk8/3/0/LocalFile.CreateABTest_CreateABTestByBounceRate/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/56/functional-tomcat90-mysql57-jdk8/3/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/9085//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateABTest_CreateABTestByClick_">LocalFile.CreateABTest#CreateABTestByClick</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/56/functional-tomcat90-mysql57-jdk8/3/0/LocalFile.CreateABTest_CreateABTestByClick/index.html.gz">Poshi Report</a> - <a href="https://testray.life [...]

2021-08-03 13:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/56/">test-portal-acceptance-pullrequest(master)#56</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/56/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>tango<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1437">liferay-tango#1437</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551205638">[master] ci:test:tango - RitaSilveira &gt; liferay-tango - PR#1437 - 2021-08-03[03:59:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/185/">publish-testray-report#185</a><br/></div></div>

2021-08-03 13:47 UTC, CarlosBrichete commented
ci:forward

2021-08-03 13:48 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-08-03 13:48 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-08-03 13:48 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/forward-pullrequest/8//consoleFull)

2021-08-03 13:49 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/105056
[Console](https://test-1-26.liferay.com/job/forward-pullrequest/8//consoleFull)

2021-08-03 13:49 UTC, closed without merging