LPS-131187 Add getType method to ContentDashboardIntem interface
liferay-tango/liferay-portal pull request #1461
Opened 2021-07-26 12:06 UTC by YurenaC

- LPS-119966 Adding basic support for documents
- LPS-119966 FileEntries are indexed as DLFileEntry
- LPS-119966 Implementing actions for documents
- LPS-119966 Indexing DLFileEntryTypes
- LPS-119966 Applying classNameId filter only to DDM structures
- LPS-119966 Only returning the latest versions (approved and draft)
- LPS-119966 Feature flagging
- LPS-119966 Sort params alphabetically
- LPS-119966 Renaming getInfoItemFieldValue to getInfoFieldValue so the method name match the interface class that is returned - Keeping old method deprecated in order to allow compatibility with user custom implementations
- LPS-119966 Also change variables
- LPS-119966 Sort
- LPS-119966 inline
- LPS-119966 SF
- LPS-119966 Sorted params for FileEntryContentDashboardItem constructor
- LPS-119966 Sorted params for ViewFileEntryContentDashboardItemAction constructor
- LPS-119966 Sorted params for JournalArticleContentDashboardItem constructor
- LPS-119966 Sorted params for RenderLayoutStructureDisplayContext constructor
- LPS-119966 Sorted params for JournalArticleContentDashboardItem constructor
- LPS-119966 Baseline Fix
- LPS-131187 Added getType method to ContentDashboardItem interface - Added getType method to inteface's implementations
- LPS-131187 Modifying tests to check getType method

2021-07-26 12:06 UTC, liferay-continuous-integration commented
Please only forward critical changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing 7.4 DXP EP3 & CE GA3 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-07-26 12:06 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-07-27 14:09 UTC, 4lejandrito requested changes

2021-07-27 14:09 UTC, 4lejandrito commented on modules/apps/content-dashboard/content-dashboard-web/src/main/java/com/liferay/content/dashboard/web/internal/item/ContentDashboardItem.java
> +	public String getType();
As discussed on Slack, this must be locale dependent.

2021-07-27 14:13 UTC, 4lejandrito commented on modules/apps/content-dashboard/content-dashboard-web/src/main/java/com/liferay/content/dashboard/web/internal/item/ContentDashboardItem.java
> +	public String getType();
Potential solution:

```java
@Override
public String getType(Locale locale) {
   String modelResourceNamePrefix =
      ResourceActionsUtil.getModelResourceNamePrefix();
   String key = modelResourceNamePrefix.concat(FileEntry.class.getName());
   return LanguageUtil.get(locale, key, null);
}
```

2021-07-28 11:34 UTC, YurenaC commented
View https://github.com/liferay-tango/liferay-portal/pull/1465

2021-07-28 11:34 UTC, closed without merging