LPS-122873
liferay-tango/liferay-portal pull request #1480
Opened 2021-07-30 23:37 UTC by RitaSilveira

2021-07-30 23:37 UTC, liferay-continuous-integration commented
Please only forward critical changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing 7.4 DXP EP3 & CE GA3 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-07-30 23:45 UTC, RitaSilveira commented
ci:test:sf

2021-07-30 23:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/282/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-source-format/builds/282/jenkins-report.html">here</a>.</b></p>

2021-07-30 23:49 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RitaSilveira/liferay-portal/tree/LPS-122873">LPS-122873</a><br/>Branch GIT ID: <a href="https://github.com/RitaSilveira/liferay-portal/commit/838e6e95aeb5ecae1458b3fc6cbc19b2c15a023f">838e6e95aeb5ecae1458b3fc6cbc19b2c15a023f</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/282/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/282/jenkins-report.html">here</a>.</h5><div><p>POSHI Validation Failure<pre><code>     [exec] 1 errors in Poshi script syntax
     [exec] 
     [exec] Unexpected closing boundary at:
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase:2506
     [exec]     @description = "LPS-122873 When the user uncheck any checkbox from the vocab2, the relative ordering of the categories remain the same") \{
     [exec]                                                                                                                                            ^
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':validatePoshi'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org
     [exec] 
     [exec] BUILD FAILED</code></pre></p></div></details></html>

2021-07-30 23:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/282/">test-portal-source-format#282</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/282/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1480">liferay-tango#1480</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1550782819">[master] ci:test:sf - RitaSilveira &gt; liferay-tango - PR#1480 - 2021-07-30[16:45:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/881/">publish-testray-report#881</a><br/></div></div>

2021-07-30 23:56 UTC, RitaSilveira commented
ci:test:sf

2021-07-30 23:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/657/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-source-format/builds/657/jenkins-report.html">here</a>.</b></p>

2021-07-31 00:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RitaSilveira/liferay-portal/tree/LPS-122873">LPS-122873</a><br/>Branch GIT ID: <a href="https://github.com/RitaSilveira/liferay-portal/commit/f603c238b5854ab70bd95daa9d997e624c84a947">f603c238b5854ab70bd95daa9d997e624c84a947</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/657/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/657/jenkins-report.html">here</a>.</h5></details></html>

2021-07-31 00:01 UTC, RitaSilveira commented
ci:test:tango

2021-07-31 00:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/657/">test-portal-source-format#657</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/657/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1480">liferay-tango#1480</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1550782857">[master] ci:test:sf - RitaSilveira &gt; liferay-tango - PR#1480 - 2021-07-30[16:57:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/1335/">publish-testray-report#1335</a><br/></div></div>

2021-07-31 00:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>tango</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/299/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/299/jenkins-report.html">here</a>.</b></p>

2021-07-31 01:34 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:tango - 4 out of 8 jobs passed in 1 hour 33 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2168">Acceptance Upstream DXP (master) #2168</a></p><details><summary><strong>ci:test:tango - 4 out of 8 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/299/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3116/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6355/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9071/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/627/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/502/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/626/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/501/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/299/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9071/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/9071//consoleText">AXIS_VARIABLE=2,label_exp=!master #9071</a><pre><code>     [exec] * What went wrong:
     [exec] Execution failed for task ':dxp:apps:osb:osb-faro:osb-faro-theme:gulpBuild'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/com-liferay-osb-faro-private/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org
     [exec] 
     [exec] BUILD FAILED in 4s
     [exec] 
     [exec] &gt; Task :dxp:apps:osb:osb-faro:osb-faro-theme:gulpBuild FAILED
     [exec] [18:23:48] Using gulpfile /opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/gulpfile.js
     [exec] [18:23:48] Starting 'build'...
     [exec] [18:23:48] Starting 'build:clean'...
     [exec] [18:23:48] Finished 'build:clean' after 122 ms
     [exec] [18:23:48] Starting 'build:base'...
     [exec] [18:23:48] Finished 'build:base' after 641 ms
     [exec] [18:23:48] Starting 'build:src'...
     [exec] [18:23:48] Finished 'build:src' after 7.72 ms
     [exec] [18:23:48] Starting 'build:web-inf'...
     [exec] [18:23:48] Finished 'build:web-inf' after 1.5 ms
     [exec] [18:23:48] Starting 'build:liferay-look-and-feel'...
     [exec] [18:23:48] Finished 'build:liferay-look-and-feel' after 11 ms
     [exec] [18:23:48] Starting 'build:hook'...
     [exec] [18:23:48] Finished 'build:hook' after 4.16 ms
     [exec] [18:23:48] Starting 'build:themelets'...
     [exec] [18:23:48] Starting 'build:themelet-src'...
     [exec] [18:23:48] Finished 'build:themelet-src' after 605 ??s
     [exec] [18:23:48] Starting 'build:themelet-css-inject'...
     [exec] [18:23:48] Starting 'build:themelet-js-inject'...
     [exec] [18:23:48] &#27;[35mgulp-inject&#27;[39m Nothing to inject into &#27;[35m_custom.scss&#27;[39m.
     [exec] [18:23:48] &#27;[35mgulp-inject&#27;[39m Nothing to inject into &#27;[35mportal_normal.ftl&#27;[39m.
     [exec] [18:23:48] Finished 'build:themelet-js-inject' after 7.12 ms
     [exec] [18:23:48] Finished 'build:themelet-css-inject' after 27 ms
     [exec] [18:23:48] Finished 'build:themelets' after 28 ms
     [exec] [18:23:48] Starting 'build:rename-css-dir'...
     [exec] [18:23:48] Finished 'build:rename-css-dir' after 127 ??s
     [exec] [18:23:48] Starting 'build:compile-css'...
     [exec] [18:23:48] Starting 'build:compile-lib-sass'...</code></pre></div></li><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/9071//consoleText">AXIS_VARIABLE=0,label_exp=!master #9071</a><ol><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/9071//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateABTest_CreateABTestByBounceRate_">LocalFile.CreateABTest#CreateABTestByBounceRate</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-28/test-portal-acceptance-pullrequest(master)/299/functional-tomcat90-mysql57-jdk8/3/0/LocalFile.CreateABTest_CreateABTestByBounceRate/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-28/test-portal-acceptance-pullrequest(master)/299/functional-tomcat90-mysql57-jdk8/3/0/LocalFile.CreateABTest_CreateABTestByBounceRate/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-28/test-portal-acceptance-pullrequest(master)/299/functional-tomcat90-mysql57-jdk8/3/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/9071//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateABTest_CreateABTestByClick_">LocalFile.CreateABTest#CreateABTestByClick</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-28/test-portal-acceptance-pullrequest(master)/299/functional-tomcat90-mysql57-jdk8/3/0/LocalFile.CreateABTest_CreateABTestByClick/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-28/test-portal-acceptance-pullrequest(master)/299/functional-tomcat90-mysql57-jdk8/3/0/LocalFile.CreateABTest_CreateABTestByClick/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-28/test-portal-acceptance-pullrequest(master)/299/functional-tomcat90-mysql57-jdk8/3/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div [...]

2021-07-31 01:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/299/">test-portal-acceptance-pullrequest(master)#299</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/299/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>tango<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1480">liferay-tango#1480</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1550791503">[master] ci:test:tango - RitaSilveira &gt; liferay-tango - PR#1480 - 2021-07-30[17:01:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/882/">publish-testray-report#882</a><br/></div></div>

2021-08-02 15:19 UTC, RitaSilveira commented
ci:test:sf

2021-08-02 15:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/39/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-source-format/builds/39/jenkins-report.html">here</a>.</b></p>

2021-08-02 15:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RitaSilveira/liferay-portal/tree/LPS-122873">LPS-122873</a><br/>Branch GIT ID: <a href="https://github.com/RitaSilveira/liferay-portal/commit/970c0406cecfda6368141cda497c171f37a3589a">970c0406cecfda6368141cda497c171f37a3589a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/39/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/39/jenkins-report.html">here</a>.</h5></details></html>

2021-08-02 15:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/39/">test-portal-source-format#39</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/39/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1480">liferay-tango#1480</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551038836">[master] ci:test:sf - RitaSilveira &gt; liferay-tango - PR#1480 - 2021-08-02[08:19:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/132/">publish-testray-report#132</a><br/></div></div>

2021-08-02 15:24 UTC, RitaSilveira commented
ci:test:tango

2021-08-02 15:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>tango</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/40/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/40/jenkins-report.html">here</a>.</b></p>

2021-08-02 17:47 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:tango - 4 out of 8 jobs passed in 2 hours 23 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2168">Acceptance Upstream DXP (master) #2168</a></p><details><summary><strong>ci:test:tango - 4 out of 8 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/40/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25908/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/788/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9078/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6539/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25907/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6540/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6541/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/40/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25908/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>133 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=19,label_exp=!master/25908//consoleText">AXIS_VARIABLE=19,label_exp=!master #25908</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=19,label_exp=!master/25908//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ContentDashboardAuditGraph_KeepInfomationOfDeleteVocabularyInSegment_">LocalFile.ContentDashboardAuditGraph#KeepInfomationOfDeleteVocabularyInSegment</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/40/functional-tomcat90-mysql57-jdk8/0/19/LocalFile.ContentDashboardAuditGraph_KeepInfomationOfDeleteVocabularyInSegment/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/40/functional-tomcat90-mysql57-jdk8/0/19/LocalFile.ContentDashboardAuditGraph_KeepInfomationOfDeleteVocabularyInSegment/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/40/functional-tomcat90-mysql57-jdk8/0/19/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=24,label_exp=!master/25908//consoleText">AXIS_VARIABLE=24,label_exp=!master #25908</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=24,label_exp=!master/25908//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ExperienceCreateExperience_AddNewExperienceSessionLanguageSegment_">LocalFile.ExperienceCreateExperience#AddNewExperienceSessionLanguageSegment</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/40/functional-tomcat90-mysql57-jdk8/0/24/LocalFile.ExperienceCreateExperience_AddNewExperienceSessionLanguageSegment/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/40/functional-tomcat90-mysql57-jdk8/0/24/LocalFile.ExperienceCreateExperience_AddNewExperienceSessionLanguageSegment/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/40/functional-tomcat90-mysql57-jdk8/0/24/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9078/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></h5><div><h6>Job Results:</h6><p>3 Tests Passed.<br/>5 Tests Failed.</p></div><ol><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/9078//consoleText">AXIS_VARIABLE=0,label_exp=!master #9078</a><ol><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/9078//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateABTest_CreateABTestByBounceRate_">LocalFile.CreateABTest#CreateABTestByBounceRate</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/40/functional-tomcat90-mysql57-jdk8/3/0/LocalFile.CreateABTest_CreateABTestByBounceRate/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/40/functional-tomcat90-mysql57-jdk8/3/0/LocalFile.CreateABTest_CreateABTestByBounceRate/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/40/functional-tomcat90-mysql57-jdk8/3/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/9078//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateABTest_CreateABTestByClick_">LocalFile.CreateABTest#CreateABTestByClick</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/40/functional-tomcat90-mysql57-jdk8/3/0/LocalFile.CreateABTest_CreateABTestByClick/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/40/functional-tomcat90-mysql57-jdk8/3/0/LocalFile. [...]

2021-08-02 17:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/40/">test-portal-acceptance-pullrequest(master)#40</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/40/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>tango<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1480">liferay-tango#1480</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551077850">[master] ci:test:tango - RitaSilveira &gt; liferay-tango - PR#1480 - 2021-08-02[08:24:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/140/">publish-testray-report#140</a><br/></div></div>

2021-08-03 13:07 UTC, CarlosBrichete requested changes

2021-08-03 13:07 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +	test ReversingTheAxesUsingTheFlipButton {
This test is not needed, there is already a test testing this, called FlipAxesButton. You can delete it.

2021-08-03 13:07 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		property portal.acceptance = "true";
Change the title of this test, is not easy to know what it does. Dont refer it to concrete names, it has to say something related with the order or something like that

2021-08-03 13:07 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +	test CategoriesForVocab1 {
Change the title of this test, is not easy to know what it does. Dont refer it to concrete names

2021-08-03 13:07 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +	test ANewCategory {
Change the title of this test, is not easy to know what it does.

2021-08-03 13:07 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +	test SlelectSomeCategoriesFromVocab1 {
Change the title of this test, is not easy to know what it does. Dont refer it to concrete names. Also it has a mistake in the Select

2021-08-03 13:07 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +	@priority = "5"
Also review the priority of all of the tests. All of them are Critical=FP5??
Remember:
* Critical: FP5
* High: FP4
* Medium: FP3

2021-08-04 03:41 UTC, RitaSilveira commented
fixed

2021-08-04 08:15 UTC, CarlosBrichete requested changes

2021-08-04 08:15 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		}
Here you say that it navigates and check the category order, color and last position, but you are just navigating. Where are the asserts?

2021-08-04 08:15 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		}
Here you say that it navigates and check the category order but you are just navigating. Where are the asserts?

2021-08-04 08:15 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		property portal.acceptance = "true";
This name remains the same, please modify.

2021-08-04 08:15 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		}
Here you say that it navigates and check the category order but you are just navigating. Where are the asserts?

2021-08-04 08:15 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		}
Here you say that it navigates and check the category order but you are just navigating. Where are the asserts?

2021-08-04 08:15 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +			}
Can this be done in a macro?

2021-08-04 08:15 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		}
Here you say that it navigates and check the category order but you are just navigating. Where are the asserts?

2021-08-04 08:15 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		}
Here you say that it navigates and check the category order but you are just navigating and unchecking the checkbox. Where are the asserts?

2021-08-04 08:15 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +			}
Can this be done in a macro?

2021-08-04 08:15 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		}
Can this be done in a macro?

2021-08-04 08:15 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +			}
Can this be done in a macro?

2021-08-04 08:15 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +			}
Can this be done in a macro?

2021-08-04 08:15 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		}
Can this be done in a macro?

2021-08-04 08:16 UTC, CarlosBrichete commented
hey @RitaSilveira, please review my comments

2021-08-06 06:35 UTC, RitaSilveira commented
fixed

2021-08-06 09:26 UTC, CarlosBrichete commented
ci:test:tango

2021-08-09 07:26 UTC, CarlosBrichete commented
ci:test:tango

2021-08-09 07:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>tango</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/39/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/39/jenkins-report.html">here</a>.</b></p>

2021-08-09 11:52 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:tango - 3 out of 8 jobs passed in 4 hours 25 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8d17d473200786491e38ac7f6758b303db2c28f6">8d17d473200786491e38ac7f6758b303db2c28f6</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8d17d473200786491e38ac7f6758b303db2c28f6">8d17d473200786491e38ac7f6758b303db2c28f6</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2196">Acceptance Upstream DXP (master) #2196</a></p><details><summary><strong>ci:test:tango - 3 out of 8 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/39/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/691/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1763/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9127/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/27104/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>3 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/27106/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/690/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/27105/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/39/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9127/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/9127//consoleText">AXIS_VARIABLE=2,label_exp=!master #9127</a><pre><code>Build was aborted</code></pre></div></li><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/9127//consoleText">AXIS_VARIABLE=0,label_exp=!master #9127</a><pre><code>     [exec] * What went wrong:
     [exec] 
     [exec] Execution failed for task ':dxp:apps:osb:osb-faro:osb-faro-theme:gulpBuild'.
     [exec]     at runSequence (/opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/node_modules/run-sequence/index.js:97:2)&gt; Process 'command '/opt/dev/projects/github/com-liferay-osb-faro-private/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] 
     [exec] * Try:
     [exec]     at Gulp.&lt;anonymous&gt; (/opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/node_modules/liferay-theme-tasks/tasks/build/compile-css.js:36:3)
     [exec]     at module.exports (/opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/node_modules/orchestrator/lib/runTask.js:34:7)
     [exec]     at Gulp.Orchestrator._runTask (/opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/node_modules/orchestrator/index.js:273:3)
     [exec]     at Gulp.Orchestrator._runStep (/opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/node_modules/orchestrator/index.js:214:10)
     [exec]     at Gulp.Orchestrator.start (/opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/node_modules/orchestrator/index.js:134:8)
     [exec]     at runNextSet (/opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/node_modules/run-sequence/index.js:86:16)
     [exec]     at Gulp.onTaskEnd (/opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/node_modules/run-sequence/index.js:75:5)
     [exec]     at Gulp.emit (events.js:194:15)
     [exec]     at Gulp.Orchestrator._emitTaskDone (/opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/node_modules/orchestrator/index.js:264:8)
     [exec]     at /opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/node_modules/orchestrator/index.js:275:23
     [exec]     at finish (/opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/node_modules/orchestrator/lib/runTask.js:21:8)
     [exec]     at cb (/opt/dev/projects/github/com-liferay-osb-faro-private/osb-faro-theme/node_modules/orchestrator/lib/runTask.js:29:3)
     [exec]     at FSReqWrap.oncomplete (fs.js:141:20)
     [exec] 
     [exec] [02:57:43] 'build:compile-css' errored after 143 ms
     [exec] [02:57:43] Error in plugin 'run-sequence(build:compile-lib-sass)'
     [exec] Message:</code></pre></div></li><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/9127//consoleText">AXIS_VARIABLE=1,label_exp=!master #9127</a><ol><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/9127//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateABTest_CreateABTestByClickInvalidId_">LocalFile.CreateABTest#CreateABTestByClickInvalidId</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-32/test-portal-acceptance-pullrequest(master)/39/functional-tomcat90-mysql57-jdk8/3/1/LocalFile.CreateABTest_CreateABTestByClickInvalidId/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-32/test-portal-acceptance-pullrequest(master)/39/functional-tomcat90-mysql57-jdk8/3/1/LocalFile.CreateABTest_CreateABTestByClickInvalidId/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-32/test-portal-acceptance-pullrequest(master)/39/functional-tomcat90-mysql57-jdk8/3/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/691/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>129 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=20,label_exp=!master/691//consoleText">AXIS_VARIABLE=20,label_exp=!master #691</a><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=20,label_exp=!master/691//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ContentDashboardAuditGraph_KeepInfomationOfDeleteVoc [...]

2021-08-09 12:37 UTC, CarlosBrichete commented
ci:forward

2021-08-09 12:38 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-08-09 12:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3239/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/3239/jenkins-report.html">here</a>.</b></p>

2021-08-09 12:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/715c1a4f9cb80a6d6d143cc2f395041397313fc8">715c1a4f9cb80a6d6d143cc2f395041397313fc8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RitaSilveira/liferay-portal/tree/LPS-122873">LPS-122873</a><br/>Branch GIT ID: <a href="https://github.com/RitaSilveira/liferay-portal/commit/1de2d575434e5784be2a489c864ada35d657c36b">1de2d575434e5784be2a489c864ada35d657c36b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3239/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3239/jenkins-report.html">here</a>.</h5></details></html>

2021-08-09 12:40 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3488//consoleFull)

2021-08-09 12:40 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/3239//consoleFull)

2021-08-09 12:41 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/105241
[Console](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3488//consoleFull)

2021-08-09 12:41 UTC, closed without merging

2021-08-09 12:41 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/105242
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/3239//consoleFull)

2021-08-09 14:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/39/">test-portal-acceptance-pullrequest(master)#39</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/39/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>tango<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1480">liferay-tango#1480</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552207325">[master] ci:test:tango - RitaSilveira &gt; liferay-tango - PR#1480 - 2021-08-09[00:26:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/117/">publish-testray-report#117</a><br/></div></div>

2021-08-09 19:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3488/">test-portal-acceptance-pullrequest(master)#3488</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3488/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1480">liferay-tango#1480</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552244141">[master] ci:test:relevant - RitaSilveira &gt; liferay-tango - PR#1480 - 2021-08-09[05:38:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9835/">publish-testray-report#9835</a><br/></div></div>

2021-08-09 19:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3239/">test-portal-source-format#3239</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3239/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1480">liferay-tango#1480</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552244264">[master] ci:test:sf - RitaSilveira &gt; liferay-tango - PR#1480 - 2021-08-09[05:38:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9836/">publish-testray-report#9836</a><br/></div></div>