LPS-137227 Test Autom: Editor permission for Page Audit
liferay-tango/liferay-portal pull request #1548
Opened 2021-08-20 18:19 UTC by Luizcarlosqueiroz

2021-08-20 18:19 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-08-20 18:21 UTC, Luizcarlosqueiroz commented
@CarlosBrichete

2021-08-23 08:08 UTC, CarlosBrichete requested changes

2021-08-23 08:08 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/pageaudit/PageAudit.testcase
> +		}
This should be included in the teardown, not in the test.
For the line _JSONUser.tearDownNonAdminUsers();_, you can just included it in the teardown.
For the line **JSONRole.deleteRole(roleTitle = "BlogsEditorRole");**, if you add the line _Role.tearDownCP();_ in the teardown, all roles with the word "Name" in the name of the role will be deleted, so I would include this line in the teardown and modify all the role names, to include the word "Name" :)

2021-08-23 08:08 UTC, CarlosBrichete commented
Hey @Luizcarlosqueiroz , please modify the tests with the review comment, thank you :)

2021-08-23 12:42 UTC, Luizcarlosqueiroz commented
Hey @CarlosBrichete! Tests modified.

2021-08-23 12:57 UTC, CarlosBrichete commented
ci:test:tango

2021-08-23 12:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>tango</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3640/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3640/jenkins-report.html">here</a>.</b></p>

2021-08-23 13:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:tango - 0 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5dd3733560bd8cb9f6bbc886255c7b074fc0b768">5dd3733560bd8cb9f6bbc886255c7b074fc0b768</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2705e9c839473db55e9c2a85317fe8d570ceebb1">2705e9c839473db55e9c2a85317fe8d570ceebb1</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2242">Acceptance Upstream DXP (master) #2242</a></p><details><summary><strong>ci:test:tango - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3640/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3640/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3640/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-08-23 13:07 UTC, CarlosBrichete commented
ci:test:tango

2021-08-23 13:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>tango</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3642/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3642/jenkins-report.html">here</a>.</b></p>

2021-08-23 13:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:tango - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5dd3733560bd8cb9f6bbc886255c7b074fc0b768">5dd3733560bd8cb9f6bbc886255c7b074fc0b768</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2705e9c839473db55e9c2a85317fe8d570ceebb1">2705e9c839473db55e9c2a85317fe8d570ceebb1</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2242">Acceptance Upstream DXP (master) #2242</a></p><details><summary><strong>ci:test:tango - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3642/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3642/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3642/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-08-23 13:53 UTC, CarlosBrichete commented
ci:test:tango

2021-08-23 13:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>tango</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3644/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3644/jenkins-report.html">here</a>.</b></p>

2021-08-23 13:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:tango - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5dd3733560bd8cb9f6bbc886255c7b074fc0b768">5dd3733560bd8cb9f6bbc886255c7b074fc0b768</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2705e9c839473db55e9c2a85317fe8d570ceebb1">2705e9c839473db55e9c2a85317fe8d570ceebb1</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2242">Acceptance Upstream DXP (master) #2242</a></p><details><summary><strong>ci:test:tango - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3644/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3644/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3644/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-08-23 14:08 UTC, ling-alan-huang commented
ci:test:sf

2021-08-23 14:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/361/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com//userContent/jobs/test-portal-source-format/builds/361/jenkins-report.html">here</a>.</b></p>

2021-08-23 14:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6f4e7970083a0f4c8181f0613382167f3a41f14e">6f4e7970083a0f4c8181f0613382167f3a41f14e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/tree/LPS-137227-TA">LPS-137227-TA</a><br/>Branch GIT ID: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/commit/812ecc76ee431729af4bd820b15fb0391c93336a">812ecc76ee431729af4bd820b15fb0391c93336a</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/361/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/361/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/pageaudit/PageAudit.testcase expected:&lt;...SS_BAR");
     [java] 		\}
     [java] 	\}
     [java] 
     [java] 	@[priority = "3"
     [java] 	test CheckErrorDetailsDisplayedInvalidApiKey \{
     [java] 		property test.name.skip.portal.instance = "PageAudit#CheckErrorDetailsDisplayedInvalidApiKey";
     [java] 
     [java] 		task ("Enable Google PageSpeed") \{
     [java] 			PageAudit.enableGooglePageSpeed();
     [java] 
     [java] 			Refresh();
     [java] 		\}
     [java] 
     [java] 		task ("Set Google PageSpeed API") \{
     [java] 			PageAudit.setAPIViaSystemSettings(apiKey = "invalidAPI");
     [java] 
     [java] 			Alert.viewSuccessMessage();
     [java] 		\}
     [java] 
     [java] 		task ("Open Page Audit panel and assert 'Show details' link") \{
     [java] 			Navigator.openWithAppendToBaseURL(urlAppend = "web/test-site-name/content-page");
     [java] 
     [java] 			PageAudit.openPanelAfterConfiguration(pageName = "Content Page");
     [java] 
     [java] 			WaitForElementPresent(
     [java] 				errorTitle = "The API key is invalid.",
     [java] 				locator1 = "PageAudit#ERROR_WARNING_TITLE");
     [java] 
     [java] 			Button.click(button = "Show Details");
     [java] 
     [java] 			AssertElementPresent(
     [java] 				errorMessage = "API key not valid. Please pass a valid API key.",
     [java] 				locator1 = "PageAudit#ERROR_WARNING_MESSAGE");
     [java] 		\}
     [java] 	\}
     [java] 
     [java] 	@priority = "4"
     [java] 	@uitest
     [java] 	test CheckIllegibleFontSizes \{
     [java] 		property portal.acceptance = "true";
     [java] 		property test.name.skip.portal.instance = "PageAudit#CheckIllegibleFontSizes";
     [java] 
     [java] 		task ("Set a custom page as canonical URL to have data already loaded") \{
     [java] 			PageAudit.setSEOcanonicalURL(URL = "https://liferay-tango.github.io/liferay-portal/page-audit-test");
     [java] 		\}
     [java] 
     [java] 		task ("Enable Google PageSpeed") \{
     [java] 			PageAudit.enableGooglePageSpeed();
     [java] 		\}
     [java] 
     [java] 		task ("Set Google PageSpeed API") \{
     [java] 			Navigator.openWithAppendToBaseURL(urlAppend = "web/test-site-name/content-page");
     [java] 
     [java] 			PageAudit.setAPIViaSiteSettings(apiKey = "AIzaSyAq-oKsvIhlYHdk1UXCFy63h74ECIgbgbE");
     [java] 		\}
     [java] </code></pre></details></html>

2021-08-23 14:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/361/">test-portal-source-format#361</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/361/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1548">liferay-tango#1548</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1555218315">[master] ci:test:sf - Luizcarlosqueiroz &gt; liferay-tango - PR#1548 - 2021-08-23[07:09:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/1090/">publish-testray-report#1090</a><br/></div></div>

2021-08-23 17:24 UTC, ling-alan-huang commented
Sent SF fix: https://github.com/hhuijser/liferay-portal/pull/5838

2021-08-24 12:32 UTC, Luizcarlosqueiroz commented
ci:test:sf

2021-08-24 12:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/401/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-source-format/builds/401/jenkins-report.html">here</a>.</b></p>

2021-08-24 12:35 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d57aa80761a81eb279776362bea81012481b3b7e">d57aa80761a81eb279776362bea81012481b3b7e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/tree/LPS-137227-TA">LPS-137227-TA</a><br/>Branch GIT ID: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/commit/812ecc76ee431729af4bd820b15fb0391c93336a">812ecc76ee431729af4bd820b15fb0391c93336a</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/401/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/401/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/pageaudit/PageAudit.testcase expected:&lt;...won't be visible."
     [java] 	[@priority = "3"
     [java] 	test CheckNotVisibleReloadbButtonInPrivatePage \{
     [java] 		task ("Create a Private Page") \{
     [java] 			JSONLayout.addPrivateLayout(
     [java] 				groupName = "Test Site Name",
     [java] 				layoutName = "Private Page Name");
     [java] 		\}
     [java] 
     [java] 		task ("Go to Private Page") \{
     [java] 			Navigator.gotoPrivateSitePage(
     [java] 				pageName = "Private Page Name",
     [java] 				siteName = "Test Site Name");
     [java] 		\}
     [java] 
     [java] 		task ("Open Page Audit tab and Assert reload button id not present") \{
     [java] 			PageAudit.openPanelBeforeConfiguration();
     [java] 
     [java] 			IsElementPresent(locator1 = "PageAudit#ERROR_WARNING_BOX");
     [java] 
     [java] 			IsElementNotPresent(locator1 = "PageAudit#RELAUNCH_PAGE_AUDIT_BUTTON");
     [java] 		\}
     [java] 	\}
     [java] 
     [java] 	@description = "Given the Page Audit panel in a private page
     [java] 	Then the reload button won't be visible."
     [java] 	@priority = "3"
     [java] 	test CheckNotVisibleReloadbButtonInPrivatePage \{
     [java] 		task ("Create a Private Page") \{
     [java] 			JSONLayout.addPrivateLayout(
     [java] 				groupName = "Test Site Name",
     [java] 				layoutName = "Private Page Name");
     [java] 		\}
     [java] 
     [java] 		task ("Go to Private Page") \{
     [java] 			Navigator.gotoPrivateSitePage(
     [java] 				pageName = "Private Page Name",
     [java] 				siteName = "Test Site Name");
     [java] 		\}
     [java] 
     [java] 		task ("Open Page Audit tab and Assert reload button id not present") \{
     [java] 			PageAudit.openPanelBeforeConfiguration();
     [java] 
     [java] 			IsElementPresent(locator1 = "PageAudit#ERROR_WARNING_BOX");
     [java] 
     [java] 			IsElementNotPresent(locator1 = "PageAudit#RELAUNCH_PAGE_AUDIT_BUTTON");
     [java] 		\}
     [java] 	\}
     [java] 
     [java] 	@description = "LPS-137227 Given a content page	When a user with permissions to edit blogs visits the page Then the issue icon for displaying the page audit panel shows"
     [java] 	@priority = "4"
     [java] 	test CheckPageAuditIconInContentPageWithEditBlogsPermission \{
     [java] 		task ("Create user") \{</code></pre></details></html>

2021-08-24 12:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/401/">test-portal-source-format#401</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/401/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1548">liferay-tango#1548</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1555487059">[master] ci:test:sf - Luizcarlosqueiroz &gt; liferay-tango - PR#1548 - 2021-08-24[05:33:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/1128/">publish-testray-report#1128</a><br/></div></div>

2021-08-24 12:49 UTC, Luizcarlosqueiroz commented
ci:test:sf

2021-08-24 12:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/384/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com//userContent/jobs/test-portal-source-format/builds/384/jenkins-report.html">here</a>.</b></p>

2021-08-24 12:50 UTC, Luizcarlosqueiroz commented
@CarlosBrichete Just to leave a record of it, as seen in ci:test:sf, `CheckNotVisibleReloadbButtonInPrivatePage` test was duplicated. I removed one of them.

2021-08-24 12:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d57aa80761a81eb279776362bea81012481b3b7e">d57aa80761a81eb279776362bea81012481b3b7e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/tree/LPS-137227-TA">LPS-137227-TA</a><br/>Branch GIT ID: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/commit/9d55ada2dd338c310a2962b71ed7d8e5de302131">9d55ada2dd338c310a2962b71ed7d8e5de302131</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/384/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/384/jenkins-report.html">here</a>.</h5></details></html>

2021-08-24 12:53 UTC, Luizcarlosqueiroz commented
ci:test:tango

2021-08-24 12:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/384/">test-portal-source-format#384</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/384/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1548">liferay-tango#1548</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1555488084">[master] ci:test:sf - Luizcarlosqueiroz &gt; liferay-tango - PR#1548 - 2021-08-24[05:49:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/1156/">publish-testray-report#1156</a><br/></div></div>

2021-08-24 12:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>tango</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/420/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/420/jenkins-report.html">here</a>.</b></p>

2021-08-24 17:52 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 48 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.NullPointerException
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d57aa80761a81eb279776362bea81012481b3b7e">d57aa80761a81eb279776362bea81012481b3b7e</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/420/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/420/jenkins-report.html">here</a>.</b></p>

2021-08-24 17:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/420/">test-portal-acceptance-pullrequest(master)#420</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/420/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>tango<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1548">liferay-tango#1548</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1555594246">[master] ci:test:tango - Luizcarlosqueiroz &gt; liferay-tango - PR#1548 - 2021-08-24[05:53:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/1141/">publish-testray-report#1141</a><br/></div></div>

2021-08-25 07:54 UTC, CarlosBrichete commented
ci:test:tango

2021-08-25 08:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>tango</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8659/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8659/jenkins-report.html">here</a>.</b></p>

2021-08-25 12:38 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:tango - 4 out of 9 jobs passed in 4 hours 40 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a5f3fe337ec76d6551d36d20d624a66cbde9a700">a5f3fe337ec76d6551d36d20d624a66cbde9a700</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a5f3fe337ec76d6551d36d20d624a66cbde9a700">a5f3fe337ec76d6551d36d20d624a66cbde9a700</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2257">Acceptance Upstream DXP (master) #2257</a></p><details><summary><strong>ci:test:tango - 4 out of 9 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8659/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12460/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5994/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30868/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9283/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</strong></strike></a></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9072/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12459/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30866/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30867/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8659/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9283/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>0 Tests Failed.</p></div><ol><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/9283//consoleText">AXIS_VARIABLE=2 #9283</a><pre><code>Build was aborted</code></pre></div></li><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/9283//consoleText">AXIS_VARIABLE=0 #9283</a><ol><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/9283//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateABTest_CreateABTestByBounceRate_">LocalFile.CreateABTest#CreateABTestByBounceRate</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/4/0/LocalFile.CreateABTest_CreateABTestByBounceRate/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/4/0/LocalFile.CreateABTest_CreateABTestByBounceRate/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/4/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/9283//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateABTest_CreateABTestByClick_">LocalFile.CreateABTest#CreateABTestByClick</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/4/0/LocalFile.CreateABTest_CreateABTestByClick/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/4/0/LocalFile.CreateABTest_CreateABTestByClick/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/4/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/9283//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateABTest_CreateABTestRunWithNoVariants_">LocalFile.CreateABTest#CreateABTestRunWithNoVariants</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/4/0/LocalFile.CreateABTest_CreateABTestRunWithNoVariants/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/4/0/LocalFile.CreateABTest_CreateABTestRunWithNoVariants/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/4/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/9283//consoleText">AXIS_VARIABLE=1 #9283</a><ol><li><div><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/9283//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateABTest_CreateABTestByClickInvalidId_">LocalFile.CreateABTest#CreateABTestByClickInvalidId</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/4/1/LocalFile.CreateABTest_CreateABTestByClickInvalidId/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/4/1/LocalFile.CreateABTest_CreateABTestByClickInvalidId/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/4/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12460/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>128 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=22/12460//consoleText">AXIS_VARIABLE=22 #12460</a><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=22/12460//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ [...]

2021-08-25 12:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8659/">test-portal-acceptance-pullrequest(master)#8659</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8659/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>tango<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1548">liferay-tango#1548</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1555980753">[master] ci:test:tango - Luizcarlosqueiroz &gt; liferay-tango - PR#1548 - 2021-08-25[00:58:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-16.liferay.com/job/publish-testray-report/1666/">publish-testray-report#1666</a><br/></div></div>

2021-08-25 13:31 UTC, CarlosBrichete commented
ci:forward

2021-08-25 13:31 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-08-25 13:31 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-08-25 13:32 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/forward-pullrequest/553//consoleFull)

2021-08-25 13:32 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/106135
[Console](https://test-1-25.liferay.com/job/forward-pullrequest/553//consoleFull)

2021-08-25 13:32 UTC, closed without merging