LPS-139257
liferay-tango/liferay-portal pull request #1890
Opened 2021-11-30 23:46 UTC by lucassantanasantos

2021-11-30 23:46 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-11-30 23:47 UTC, lucassantanasantos commented
@CarlosBrichete

2021-12-01 09:22 UTC, CarlosBrichete requested changes

2021-12-01 09:22 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentperformance/ContentPerformanceWithoutAC.testcase
> +			Click(locator1 = "ContentPerformance#ICON_VIEW_METRICS");
This should be included in a macro, try to not have clicks within the testcase file.

2021-12-01 09:23 UTC, CarlosBrichete commented
ci:test:sf

2021-12-01 09:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/220/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/220/jenkins-report.html">here</a>.</b></p>

2021-12-01 09:27 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c49165737a2ea25992172d10b00afc89263b56a1">c49165737a2ea25992172d10b00afc89263b56a1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lucassantanasantos/liferay-portal/tree/LPS-139257">LPS-139257</a><br/>Branch GIT ID: <a href="https://github.com/lucassantanasantos/liferay-portal/commit/856c34d8b9613b315944336f22b486da57c93857">856c34d8b9613b315944336f22b486da57c93857</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/220/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/220/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentperformance/ContentPerformanceWithoutAC.testcase expected:&lt;... this again.");
     [java] 		\}
     [java] []	\}
     [java] 
     [java] 	@description = ...&gt; but was:&lt;... this again.");
     [java] 		\}
     [java] [
     [java] ]	\}
     [java] 
     [java] 	@description = ...&gt;
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:458)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:287)
[stopwatch] [run.batch.test.action: 2:50.355 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:555: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:689: Java returned: 1
      [get] Getting: http://test-1-35/job/test-portal-source-format/220//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20211201012719904.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20211201012719904.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null906867631.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null821333291
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 395ms
[junitreport] Deleting: /tmp/null821333291
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 12-01-2021 01:27:22:087 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</code></pre></details></html>

2021-12-01 09:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/220/">test-portal-source-format#220</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/220/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1890">liferay-tango#1890</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1585779179">[master] ci:test:sf - lucassantanasantos &gt; liferay-tango - PR#1890 - 2021-12-01[01:23:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/840/">publish-testray-report#840</a><br/></div></div>

2021-12-01 09:33 UTC, CarlosBrichete commented
Also the SF is failing, please review it, thanks 😊

2021-12-01 19:22 UTC, CarlosBrichete commented
ci:test:sf

2021-12-01 19:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/1122/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1122/jenkins-report.html">here</a>.</b></p>

2021-12-01 19:26 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/215417a0057bdf4ed0bbe961b384ffa52ecf4e09">215417a0057bdf4ed0bbe961b384ffa52ecf4e09</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lucassantanasantos/liferay-portal/tree/LPS-139257">LPS-139257</a><br/>Branch GIT ID: <a href="https://github.com/lucassantanasantos/liferay-portal/commit/856c34d8b9613b315944336f22b486da57c93857">856c34d8b9613b315944336f22b486da57c93857</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/1122/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1122/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentperformance/ContentPerformanceWithoutAC.testcase expected:&lt;... this again.");
     [java] 		\}
     [java] []	\}
     [java] 
     [java] 	@description = ...&gt; but was:&lt;... this again.");
     [java] 		\}
     [java] [
     [java] ]	\}
     [java] 
     [java] 	@description = ...&gt;
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:458)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:287)
[stopwatch] [run.batch.test.action: 2:42.354 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:555: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:689: Java returned: 1
      [get] Getting: http://test-1-30/job/test-portal-source-format/1122//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20211201112638202.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20211201112638202.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null988297679.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1837485308
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 175ms
[junitreport] Deleting: /tmp/null1837485308
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 12-01-2021 11:26:40:633 PST
[stopwatch] [run.batch.test.tear.down: 0.001 sec]</code></pre></details></html>

2021-12-01 19:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/1122/">test-portal-source-format#1122</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1122/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/1890">liferay-tango#1890</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1586027202">[master] ci:test:sf - lucassantanasantos &gt; liferay-tango - PR#1890 - 2021-12-01[11:22:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/3742/">publish-testray-report#3742</a><br/></div></div>

2021-12-01 19:31 UTC, CarlosBrichete commented
@lucassantanasantos The SF failure seems to be related to your PR, could you please review?

2021-12-01 19:47 UTC, closed without merging