LPS-130919 Move configure Session Property Vocabularies from System Settings to Instance Settings
liferay-tango/liferay-portal pull request #2284
Opened 2022-03-14 15:00 UTC by YurenaC

- LPS-77699 Update Translations
- LRQA-65826 remove the workaround
- LRQA-73634 Combine the two Jboss batches
- LPS-148767 Disable JavaAPISignatureCheck check
- LPS-148767 Remove suppressions
- LPS-148767 Remove source-formatter-suppressions.xml
- LPS-148767 Remove source-formatter-api-signature-check-exceptions.txt
- LPS-148767 Remove JavaAPISignatureCheck
- LPS-148767 Generated
- LPS-148767 Remove markdown
- COMMERCE-8455 Auto SF
- LPS-146944 Auto SF
- LPS-149067 Rerun case on release suite
- LPS-149067 Rerun case on release suite
- LPS-149068 Refactor case and rerun on release suite
- LPS-148683 Update circulation mode for clicking info icon
- LRQA-72661 Add a workaround for LPS-148998
- LRQA-72661 Remove unnecessary steps
- LRQA-73721 Add SampleSQLBuilderTest to stable
- LRQA-73721 Sort #sfme
- LRQA-73668 Configure additional JDK11 requirements when starting Xpack
- LRQA-73668 Add assertion warning
- LPS-149019 Remove site admin web from blacklisted components
- LPS-149000 Remove MFA modules from blacklisted components
- LPS-145029 Migrate and refactor macro to edit web content via WCD then update usages
- LPS-145029 Migrate and refactor magro to addTag via WCD then update usage
- LPS-145029 Remove unneeded macro publishViaWCD and update usage
- LPS-145029 Migrate and refactor macro to view menuItem in WCD then update usages
- LPS-145029 Migrate and refactor macro to view menu item not present in WCD then update usages
- LPS-145029 Migrate and refactor macro to view related assets in WCD then update usage
- LPS-145029 Migrate macro to view with workflow in WCD and update usages
- LPS-145029 Rename macros and update usages
- LPS-145029 Rename macro and modify logic to view cannot edit WC via WCD then update usages
- LPS-145029 Rename macro to view workflow in WCD then update usages
- LPS-145029 Rename macro
- LPS-145029 Update usages
- LPS-145029 SF
- LPS-147499 Add paths for Translation Manager
- LPS-147499 Update macro to display widget on page
- LPS-147499 Add macros for Translation Manager
- LPS-147946 Add paths for Translation Manager
- LPS-147946 Add macro to delete language in Manage Translations
- LPS-147499 Add test to view translation manager language menu
- LPS-147612 Add test to view translation results displayed by different language
- LPS-147946 Add test to view language in the Manage Translation list
- LPS-147612 Update a path name
- LPS-147499 Move test files to correct module
- LPS-147499 Refactor delete language from manage translations list test
- LPS-147499 SF
- LPS-147499 Split off and refactor search language test
- LPS-147499 Format test names and tasks
- LPS-147499 Remove unnecessary test
- LPS-147499 Match testcase file name to the component name exactly
- LPS-147499 Include translation manager as testray component
- LPS-147499 SF
- LPS-147833 Copy all portlets from source layout
- LPS-148767 prep next
- LPS-148767 prep next
- POSHI-307 Use ValidationException since there's no PoshiElement
- POSHI-307 prep next
- LRCI-2846 Fix the portal release parameters to match the job factory reference
- LRCI-2846 Assign 7.4 hotfixes to liferay-portal/master
- LRCI-2846 Add support for finding the correct bundle for 7.4
- LRCI-2846 prep next
- LPS-148425 Use MT UX improvements in Clay sample
- LPS-109034 portal-search-similar-results-web: Default to asset renderer when generating result URL
- COMMERCE-8515 Fix PQL issue
- LPS-145478 Look up file entries by url title and ID
- LPS-145478 SF
- LPS-147146 New class for creating companyId column as NOT NULL on NxM tables for users upgrading from 6.2
- LPS-147146 Applying changes to NxM tables upgraded from 6.2
- LPS-147146 New class for updating column companyId to NOT NULL on NxM tables for users that already upgraded from 6.2 to 7.X
- LPS-147146 Applying changes to NxM tables for users that already upgraded from 6.2 to 7.X
- LPS-147146 Added integration tests
- LPS-147146 SF
- LPS-147146 Baseline
- LPS-147146 Manual SF
- LPS-147146 SF
- LPS-147146 Same thing
- LPS-147146 baseline
- LPS-147146 Simplify
- LPS-147146 You should probably assert the exception message string to be X, etc.
- LPS-147146 Sort
- LPS-147146 Consistency
- LPS-147146 Not needed
- LPS-147146 auto SF
- LPS-147146 Rename
- LPS-146680 Small fixes, making pattern and SF
- LPS-146680 Making possible a workflow be linked with a CommerceOrder
- LPS-148175 Create a workflow for order completion
- LPS-146680 Test of integration for workflow definition
- LPS-146680 wordsmith
- LPS-146680 Consistency
- LPS-146680 Wordsmith/SF
- LPS-146680 prevent NPE
- LPS-146680 Consistency
- LPS-148108 document-library-test: Simplify code
- LPS-148108 document-library-test: Restore code
- LPS-148108 document-library-test: sf and remove useless code
- LPS-149047 SF
- LPS-149042 Fix on assertCPOption
- COMMERCE-8651 activate upgradeProcess
- COMMERCE-8651 import permission only for new roles and account admin
- COMMERCE-8651 sort + no need to check open order
- LPS-148319 Reorganize css from TabItem
- LPS-148319 Reorganize css from TabsPanel
- LPS-148319 Reorganize css from SearchResultsPanel
- LPS-148319 Remove unnecessary FragmentSidebar file
- LPS-148319 SF
- LPS-148315 Fix prop types validation
- LPS-148315 Always render analytics_reports_panel component
- LPS-148315 Extracting reducer from component to its own file
- LPS-148315 Using a parent component for AnalyticsReports with handlers for the user events
- LPS-148315 Moving panel open/close handling from JSP to JS
- LPS-148315 Fetch initial data only on user events and when the panel is open in first load
- LPS-148315 Remove data-url and href attrs from control menu item to prevent unwanted requests
- LPS-148315 Moving specific sidenav code to hook
- LPS-148315 Format source
- LPS-148315 Moving isPanelStateOpen from backend to frontend side
- LPS-148315 Reverting: Moving panel open/close handling from JSP to JS. Some renaming that makes sense now
- LPS-148315 Fix console warnings in TrafficSources. Fix tabindex in icon
- LPS-148315 Renaming eventTriggered
- LPS-148315 Moving useInitialPanelState hook closer to usage
- LPS-148125 Creating Analytics Cloud Workspace query
- LPS-148125 Creating ActivationStatus for Analytics Cloud
- LPS-148125 Creating Analitycs Cloud Page
- LPS-148125 Creating ActivationStatusLayout component
- LPS-148125 Adding activation status date range function
- LPS-148125 Moving Analytics Cloud modal to activation status component
- LPS-148125 Adjusting status date range function with reduce
- LPS-148125 Adding groupId object field to analytics cloud
- LPS-148125 Changind workspace object group id field name
- LPS-148999 Updating Management product analytics cloud logic
- LPS-148125 upload
- LPS-148896 Pass html from previous processor to keep information
- LPS-148995 Fix false positives in tests, replacing *LocalServiceBaseImpl delete method calls with *LocalServiceImpl ones
- LPS-148486 Fix problem with the auto-save in the Notification field
- LPS-148996 Fix false positives in tests, replacing *LocalServiceBaseImpl deleteAssetCategory and deleteAssetVocabulary methods calls with *LocalServiceImpl deleteCategory and deleteVocabulary
- LPS-149048 Add Order Item Id in order request
- LPS-149048 upload
- LPS-148845 Add new EntityField on entityFieldsMap
- LPS-149054 panelCategoryRegistry will not contain the key if COMMERCE is disabled. Skip the logic if COMMERCE is disabled.
- LPS-147401 wordsmith
- LPS-146471 New ContentDashboardItemSearchClassMapper an interface that represents a mapper between the ContentDashboardItem generic class and it search class.
- LPS-146471 New Tracker for ContentDashboardItemSearchClassMappers.
- LPS-146471 Implement ContentDashboardItemSearchClassMapper for FileEntry.
- LPS-146471 Replace ContentDashboardSearchClassNameUtil with the new tracker.
- LPS-146471 Blogs Entry subtype should be selected under the search bar
- LPS-146471 Fix and add tests
- LPS-146471 Delete unused code.
- LPS-146471 Add tests.
- LPS-146471 Rename
- LPS-142254  [...]

2022-03-14 16:03 UTC, YurenaC commented
ci:test:sf

2022-03-14 16:03 UTC, YurenaC commented
ci:test:relevant

2022-03-14 16:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/401/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/401/jenkins-report.html">here</a>.</b></p>

2022-03-14 16:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/935ebdfb3b0929f56e2ef3854c5350688d69cc17">935ebdfb3b0929f56e2ef3854c5350688d69cc17</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/YurenaC/liferay-portal/tree/LPS-130919">LPS-130919</a><br/>Branch GIT ID: <a href="https://github.com/YurenaC/liferay-portal/commit/a966c55f72c8761c80abe736ac456781c824a074">a966c55f72c8761c80abe736ac456781c824a074</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/401/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/401/jenkins-report.html">here</a>.</h5></details></html>

2022-03-14 16:13 UTC, YurenaC commented
Hi @cgoncas, 
I think this changes are the simplest way to achieve our goal

Let me know your thoughts! :)

2022-03-14 16:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/401/">test-portal-source-format#401</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/401/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/2284">liferay-tango#2284</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1634273092">[master] ci:test:sf - YurenaC &gt; liferay-tango - PR#2284 - 2022-03-14[09:08:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/1647/">publish-testray-report#1647</a><br/></div></div>

2022-03-14 16:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/1365/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1365/jenkins-report.html">here</a>.</b></p>

2022-03-14 16:46 UTC, cgoncas commented
Hey @YurenaC !!

It is not posible to keep sustenta and instance settings at the same time?

thanks!!

2022-03-14 16:47 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 17 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/935ebdfb3b0929f56e2ef3854c5350688d69cc17">935ebdfb3b0929f56e2ef3854c5350688d69cc17</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e34290f69c22b81290864b086851386216bb9605">e34290f69c22b81290864b086851386216bb9605</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3026">Acceptance Upstream DXP (master) #3026</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/1365/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1365/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/1365/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>[beanshell] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-test/src/testFunctional/tests/ProcessBuilderKaleoDesignerReact.testcase: 361
[beanshell] 
[beanshell] Duplicate command name 'WorkflowMetrics#goToDashboardAllItemsWithFilter' at namespace 'LocalFile'
[beanshell] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/macros/WorkflowMetrics.macro: 850
[beanshell] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/macros/WorkflowMetrics.macro: 850
[beanshell] 
[beanshell] Duplicate command name 'WorkflowMetrics#verifyCustomCalendarExistOrNot' at namespace 'LocalFile'
[beanshell] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/macros/WorkflowMetrics.macro: 1455
[beanshell] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/macros/WorkflowMetrics.macro: 1455
[beanshell] 
[beanshell] Duplicate command name 'CustomEventsBlockEvents#CheckCannotBlockOrUnblockCustomEventsAsNonAdmin' at namespace 'LocalFile'
[beanshell] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsBlockEvents.testcase: 226
[beanshell] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsBlockEvents.testcase: 226
[beanshell] 
[beanshell] Duplicate command name 'EditSegments#SegmentListKebabMenuContainsEditAndDeleteButtons' at namespace 'LocalFile'
[beanshell] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/EditSegments.testcase: 560
[beanshell] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/EditSegments.testcase: 560
[beanshell] 
[beanshell] Duplicate command name 'Picklist#CannotLeavePicklistItemNameFieldEmpty' at namespace 'LocalFile'
[beanshell] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-test/src/testFunctional/tests/Picklist.testcase: 190
[beanshell] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-test/src/testFunctional/tests/Picklist.testcase: 190

[TRUNCATED]</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-03-14 16:48 UTC, cgoncas commented
ci:forward

2022-03-14 16:48 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-03-14 16:48 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:sf`

2022-03-14 16:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/892/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/892/jenkins-report.html">here</a>.</b></p>

2022-03-14 16:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/1365/">test-portal-acceptance-pullrequest(master)#1365</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1365/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/2284">liferay-tango#2284</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1634297516">[master] ci:test:relevant - YurenaC &gt; liferay-tango - PR#2284 - 2022-03-14[09:30:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/3783/">publish-testray-report#3783</a><br/></div></div>

2022-03-14 16:56 UTC, YurenaC commented
> Hey @YurenaC !!
> 
> It is not posible to keep system and instance settings at the same time? What are the problems that you face with this approach?
> 
> thanks!!

I kept system and instance settings and I think it works as expected.

It allows you to define a vocabulary and assign it to "Audience" for example, at system level.
Once that is done you cannot reassign that vocabulary at system level but you can do it at instance level.

Does it make sense? I'm happy to show you in a small demo tomorrow, will be easy to understand

2022-03-14 17:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 21 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/935ebdfb3b0929f56e2ef3854c5350688d69cc17">935ebdfb3b0929f56e2ef3854c5350688d69cc17</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e34290f69c22b81290864b086851386216bb9605">e34290f69c22b81290864b086851386216bb9605</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3026">Acceptance Upstream DXP (master) #3026</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/892/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/892/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/892/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>[beanshell] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/FormFields.macro: 1608
[beanshell] 
[beanshell] Duplicate command name 'Segmentation#enableAssingRolesBySegmentsCheckbox' at namespace 'LocalFile'
[beanshell] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/Segmentation.macro: 157
[beanshell] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/Segmentation.macro: 157
[beanshell] 
[beanshell] Duplicate command name 'Portlet#expandTree' at namespace 'LocalFile'
[beanshell] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/Portlet.macro: 488
[beanshell] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/Portlet.macro: 488
[beanshell] 
[beanshell] Duplicate command name 'CommercePriceLists#addNewPriceModifier' at namespace 'LocalFile'
[beanshell] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/macros/CommercePriceLists.macro: 3
[beanshell] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/macros/CommercePriceLists.macro: 3
[beanshell] 
[beanshell] Duplicate command name 'IsElementNotPresent#isElementNotPresent' at namespace 'LocalFile'
[beanshell] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/functions/IsElementNotPresent.function: 4
[beanshell] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/functions/IsElementNotPresent.function: 4
[beanshell] 
[beanshell] Duplicate command name 'DisplayPageTemplatesForCategory#SelectSpecificDisplayPageTemplateInCategoryEditor' at namespace 'LocalFile'
[beanshell] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagetemplate/displaypagetemplate/DisplayPageTemplatesForCategory.testcase: 101
[beanshell] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagetemplate/displaypagetemplate/DisplayPageTemplatesForCategory.testcase: 101
[beanshell] 
[beanshell] Duplicate command name 'EventDetails#ViewCalendarEventDetailViaMailLink' at namespace 'LocalFile'

[TRUNCATED]</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-03-14 17:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/892/">test-portal-acceptance-pullrequest(master)#892</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/892/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/2284">liferay-tango#2284</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1634321879">[master] ci:test:relevant - YurenaC &gt; liferay-tango - PR#2284 - 2022-03-14[09:48:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/2289/">publish-testray-report#2289</a><br/></div></div>

2022-03-15 07:20 UTC, YurenaC commented
ci:test:relevant

2022-03-15 08:24 UTC, YurenaC commented
ci:test:relevant

2022-03-15 08:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/2355/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2355/jenkins-report.html">here</a>.</b></p>

2022-03-15 09:56 UTC, YurenaC commented
ci:stop

2022-03-15 09:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 23 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 23 out of 28 jobs passed in 1 hour 31 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3031">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1287401_2355</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/890ab5b1cd8367a9dc066b6bf96cbfa1d2dcd48e">890ab5b1cd8367a9dc066b6bf96cbfa1d2dcd48e</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8dc731f0b8762c0dfaf7977a305c750c56d58ef7">8dc731f0b8762c0dfaf7977a305c750c56d58ef7</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3030">Acceptance Upstream DXP (master) #3030</a></p><details><summary><strong>ci:test:stable - 23 out of 27 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25306/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451090/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37302/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/491168/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/429227/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/40898/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451089/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456080/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38172/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/34278/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-wildfly180-mariadb104-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/511616/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/491169/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372881/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/39831/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/40900/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38174/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/34277/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/39829/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/39830/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37300/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/429229/">test-portal-acceptance-pullrequest-batch(master)/patching-tool-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/402068/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/429228/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38173/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/39828/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/40899/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37301/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 23 out of 28 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/2355/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25306/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451090/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37302/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/491168/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>23 Su [...]

2022-03-15 10:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/2355/">test-portal-acceptance-pullrequest(master)#2355</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2355/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/2284">liferay-tango#2284</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1634983766">[master] ci:test:relevant - YurenaC &gt; liferay-tango - PR#2284 - 2022-03-15[01:24:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/6612/">publish-testray-report#6612</a><br/></div></div>

2022-03-16 08:09 UTC, YurenaC commented
ci:test:sf

2022-03-16 08:09 UTC, YurenaC commented
ci:test:relevant

2022-03-16 08:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/1709/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/1709/jenkins-report.html">here</a>.</b></p>

2022-03-16 08:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/592af9d2d922f428016b391a35ff5adfa7fc2a02">592af9d2d922f428016b391a35ff5adfa7fc2a02</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/YurenaC/liferay-portal/tree/LPS-130919">LPS-130919</a><br/>Branch GIT ID: <a href="https://github.com/YurenaC/liferay-portal/commit/b05691ef7479795d16972b8787dda7a07a4c7e4a">b05691ef7479795d16972b8787dda7a07a4c7e4a</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/1709/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/1709/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 4 formatting issues:
     [java] 1: Chaining is allowed on 'Stream.concat', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/chaining_check.markdown: ./modules/apps/segments/segments-context-vocabulary/src/main/java/com/liferay/segments/context/vocabulary/internal/configuration/persistence/listener/SegmentsContextVocabularyConfigurationModelListener.java 140 (Checkstyle:ChainingCheck)
     [java] 2: ./modules/apps/segments/segments-context-vocabulary/src/main/java/com/liferay/segments/context/vocabulary/internal/configuration/SegmentsContextVocabularyConfiguration.java expected:&lt;...tion.metatype.Meta;
     [java] [
     [java] ]import com.liferay.p...&gt; but was:&lt;...tion.metatype.Meta;
     [java] []import com.liferay.p...&gt;
     [java] 3: ./modules/apps/segments/segments-context-vocabulary/src/main/java/com/liferay/segments/context/vocabulary/internal/configuration/persistence/listener/SegmentsContextVocabularyConfigurationModelListener.java expected:&lt;...mpanyConfiguration;
     [java] [import com.liferay.segments.context.vocabulary.internal.configuration.SegmentsContextVocabularyConfiguration;
     [java] 
     [java] import java.util.Dictionary;
     [java] import java.util.Locale;
     [java] import java.util.Objects;
     [java] import java.util.Optional;
     [java] import java.util.ResourceBundle;
     [java] import java.util.stream.Stream;
     [java] 
     [java] import org.osgi.service.cm.Configuration;
     [java] import org.osgi.service.cm.ConfigurationAdmin;
     [java] import org.osgi.service.component.annotations.Component;
     [java] import org.osgi.service.component.annotations.Reference;
     [java] 
     [java] /**
     [java]  * @author Cristina Gonz??lez
     [java]  */
     [java] @Component(
     [java]   immediate = true,
     [java]   property = \{
     [java]     "model.class.name=com.liferay.segments.context.vocabulary.internal.configuration.SegmentsContextVocabularyCompanyConfiguration",
     [java]     "model.class.name=com.liferay.segments.context.vocabulary.internal.configuration.SegmentsContextVocabularyConfiguration"
     [java]   \},
     [java]   service = ConfigurationModelListener.class
     [java] )
     [java] public class SegmentsContextVocabularyConfigurationModelListener
     [java]   implements ConfigurationModelListener \{
     [java] 
     [java]   @Override</code></pre></details></html>

2022-03-16 08:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/2181/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2181/jenkins-report.html">here</a>.</b></p>

2022-03-16 08:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/1709/">test-portal-source-format#1709</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/1709/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/2284">liferay-tango#2284</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1635817462">[master] ci:test:sf - YurenaC &gt; liferay-tango - PR#2284 - 2022-03-16[01:09:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/6282/">publish-testray-report#6282</a><br/></div></div>

2022-03-16 08:21 UTC, YurenaC commented
ci:test:sf

2022-03-16 08:21 UTC, YurenaC commented
ci:test:relevant

2022-03-16 08:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/2182/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2182/jenkins-report.html">here</a>.</b></p>

2022-03-16 08:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1540/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1540/jenkins-report.html">here</a>.</b></p>

2022-03-16 08:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/592af9d2d922f428016b391a35ff5adfa7fc2a02">592af9d2d922f428016b391a35ff5adfa7fc2a02</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/YurenaC/liferay-portal/tree/LPS-130919">LPS-130919</a><br/>Branch GIT ID: <a href="https://github.com/YurenaC/liferay-portal/commit/beb28db34336a12a8f0cdc4a941164806b99d402">beb28db34336a12a8f0cdc4a941164806b99d402</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1540/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1540/jenkins-report.html">here</a>.</h5></details></html>

2022-03-16 08:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1540/">test-portal-source-format#1540</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1540/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/2284">liferay-tango#2284</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1635827323">[master] ci:test:sf - YurenaC &gt; liferay-tango - PR#2284 - 2022-03-16[01:21:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/5571/">publish-testray-report#5571</a><br/></div></div>

2022-03-16 08:56 UTC, YurenaC commented
ci:test:relevant

2022-03-16 08:57 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 48 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.NullPointerException
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/592af9d2d922f428016b391a35ff5adfa7fc2a02">592af9d2d922f428016b391a35ff5adfa7fc2a02</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/2182/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2182/jenkins-report.html">here</a>.</b></p>

2022-03-16 08:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1017/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1017/jenkins-report.html">here</a>.</b></p>

2022-03-16 09:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/2182/">test-portal-acceptance-pullrequest(master)#2182</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2182/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/2284">liferay-tango#2284</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1635834276">[master] ci:test:relevant - YurenaC &gt; liferay-tango - PR#2284 - 2022-03-16[01:22:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/6284/">publish-testray-report#6284</a><br/></div></div>

2022-03-16 09:35 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 23 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 23 out of 28 jobs passed in 1 hour 22 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/592af9d2d922f428016b391a35ff5adfa7fc2a02">592af9d2d922f428016b391a35ff5adfa7fc2a02</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/592af9d2d922f428016b391a35ff5adfa7fc2a02">592af9d2d922f428016b391a35ff5adfa7fc2a02</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3036">Acceptance Upstream DXP (master) #3036</a></p><details><summary><strong>ci:test:stable - 23 out of 27 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38701/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/402193/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/40365/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/34698/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/40363/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41404/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/34701/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/402192/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41406/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37843/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-wildfly180-mariadb104-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/40364/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11946/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/488617/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/34700/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41409/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37841/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/34699/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37840/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38700/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41408/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/511808/">test-portal-acceptance-pullrequest-batch(master)/patching-tool-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37844/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37842/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37839/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41407/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41405/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/488616/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 23 out of 28 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/2181/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38701/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/402193/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/40365/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/34698/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/40363/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41404/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-29.li [...]

2022-03-16 09:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/2181/">test-portal-acceptance-pullrequest(master)#2181</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2181/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/2284">liferay-tango#2284</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1635905771">[master] ci:test:relevant - YurenaC &gt; liferay-tango - PR#2284 - 2022-03-16[01:11:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/6286/">publish-testray-report#6286</a><br/></div></div>

2022-03-16 11:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 23 out of 27 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 24 out of 28 jobs passed in 2 hours 15 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/592af9d2d922f428016b391a35ff5adfa7fc2a02">592af9d2d922f428016b391a35ff5adfa7fc2a02</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/592af9d2d922f428016b391a35ff5adfa7fc2a02">592af9d2d922f428016b391a35ff5adfa7fc2a02</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3036">Acceptance Upstream DXP (master) #3036</a></p><details><summary><strong>ci:test:stable - 23 out of 27 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37451/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38718/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25105/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11960/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38714/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38711/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41442/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25104/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38712/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38717/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-wildfly180-mariadb104-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37861/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16346/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11963/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11962/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/35254/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41440/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37450/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11959/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38715/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38713/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41441/">test-portal-acceptance-pullrequest-batch(master)/patching-tool-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37862/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11961/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11958/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/35253/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/35252/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38716/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 23 out of 28 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1017/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37451/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38718/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25105/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11960/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38714/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38711/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li> [...]

2022-03-16 11:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1017/">test-portal-acceptance-pullrequest(master)#1017</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1017/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/2284">liferay-tango#2284</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1635992134">[master] ci:test:relevant - YurenaC &gt; liferay-tango - PR#2284 - 2022-03-16[01:57:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/2752/">publish-testray-report#2752</a><br/></div></div>

2022-03-16 12:33 UTC, cgoncas commented on modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties
> +segments-context-vocabulary-company-configuration-asset-vocabulary-name=Vocabulary Name
The text should be the same as we use before, so no new keys needs to be added.

2022-03-16 12:35 UTC, cgoncas commented on modules/apps/segments/segments-context-vocabulary/src/main/java/com/liferay/segments/context/vocabulary/internal/field/customizer/SegmentsContextVocabularySegmentsFieldCustomizer.java
> -					SegmentsContextVocabularyConfiguration.class, properties);
You should read both, company and system configuration.

2022-03-16 12:35 UTC, cgoncas commented on modules/apps/segments/segments-context-vocabulary/src/main/java/com/liferay/segments/context/vocabulary/internal/field/customizer/SegmentsContextVocabularySegmentsFieldCustomizer.java
> -					SegmentsContextVocabularyConfiguration.class, properties);
Probably you will need a Configuration Provider, the same way we have in PageAudit

2022-03-16 12:37 UTC, cgoncas requested changes
Hey @YurenaC !!

Do you mind add some test to these changes!!

Thanks!!

2022-03-16 14:19 UTC, CarlosBrichete commented
ci:test:tango

2022-03-16 14:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>tango</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/2286/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2286/jenkins-report.html">here</a>.</b></p>

2022-03-16 15:20 UTC, CarlosBrichete commented
Hey @cgoncas I've seen that now the session property vocabularies are in Instance Settings, but they are still in System Settings too. Is this expected?

2022-03-16 15:52 UTC, cgoncas commented
> Hey @cgoncas I've seen that now the session property vocabularies are in Instance Settings, but they are still in System Settings too. Is this expected?

Yeahh @CarlosBrichete !!

I will ask Joe to update the AC, if we delete the Configuration from System then an upgrade process or something should be done for our old customers, this way it is saffer.

Thanks!!

2022-03-16 16:38 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:tango - 2 out of 10 jobs passed in 2 hours 12 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e4021bb79226947436aa10bd7bdb8f13deace8e0">e4021bb79226947436aa10bd7bdb8f13deace8e0</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e4021bb79226947436aa10bd7bdb8f13deace8e0">e4021bb79226947436aa10bd7bdb8f13deace8e0</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3037">Acceptance Upstream DXP (master) #3037</a></p><details><summary><strong>ci:test:tango - 2 out of 10 jobs PASSED</strong></summary><div><h4>8 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/2286/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25208/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16435/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/40462/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/35360/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/40441/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</strong></strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38802/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</strong></strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25207/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/34796/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/40440/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2286/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25208/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>150 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/25208//consoleText">AXIS_VARIABLE=1 #25208</a><ol><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/25208//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ABTesting_CheckABTestPanelInfoNotSyncAC_">LocalFile.ABTesting#CheckABTestPanelInfoNotSyncAC</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-portal-acceptance-pullrequest(master)/2286/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.ABTesting_CheckABTestPanelInfoNotSyncAC/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-portal-acceptance-pullrequest(master)/2286/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.ABTesting_CheckABTestPanelInfoNotSyncAC/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-portal-acceptance-pullrequest(master)/2286/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=22/25208//consoleText">AXIS_VARIABLE=22 #25208</a><ol><li><div><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=22/25208//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ContentPerformanceWithoutAC_ContentPerformanceClosed_">LocalFile.ContentPerformanceWithoutAC#ContentPerformanceClosed</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-portal-acceptance-pullrequest(master)/2286/functional-tomcat90-mysql57-jdk8/0/22/LocalFile.ContentPerformanceWithoutAC_ContentPerformanceClosed/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-portal-acceptance-pullrequest(master)/2286/functional-tomcat90-mysql57-jdk8/0/22/LocalFile.ContentPerformanceWithoutAC_ContentPerformanceClosed/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-portal-acceptance-pullrequest(master)/2286/functional-tomcat90-mysql57-jdk8/0/22/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16435/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>124 Tests Passed.<br/>10 Tests Failed.</p></div><ol><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/16435//consoleText">AXIS_VARIABLE=0 #16435</a><ol><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/16435//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ABTestWithoutACConnection_CheckABTestingClosedAfterLogout_">LocalFile.ABTestWithoutACConnection#CheckABTestingClosedAfterLogout</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-portal-acceptance-pullrequest(master)/2286/functional-tomcat90-mysql57-jdk8/1/0/LocalFile.ABTestWithoutACConnection_CheckABTestingClosedAfterLogout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-portal-acceptance-pullrequest(master)/2286/functional-tomcat90-mysql57-jdk8/1/0/LocalFile.ABTestWithoutACConnection_CheckABTestingClosedAfterLogout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-portal-acceptance-pullrequest(master)/2286/functional-tomcat90-mysql57-jdk8/1/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/16435//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ABTestWithoutACConnection_CheckHiddenABTestPanel_">LocalFile.ABTestWithoutACConnection#CheckHiddenABTestPanel</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-por [...]

2022-03-16 16:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/2286/">test-portal-acceptance-pullrequest(master)#2286</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2286/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>tango<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/2284">liferay-tango#2284</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1636220249">[master] ci:test:tango - YurenaC &gt; liferay-tango - PR#2284 - 2022-03-16[07:26:54]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/6478/">publish-testray-report#6478</a><br/></div></div>

2022-03-17 09:19 UTC, merged