LPS-150510 Test Autom. for Bug: Basic document cannot be selected in the subtype filter
liferay-tango/liferay-portal pull request #2325
Opened 2022-03-29 17:31 UTC by Luizcarlosqueiroz

2022-03-29 17:31 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-03-29 17:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/3622/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/3622/jenkins-report.html">here</a>.</b></p>

2022-03-29 17:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/3622/">test-portal-source-format#3622</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/3622/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/2325">liferay-tango#2325</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1650074697">[master] ci:test:sf - Luizcarlosqueiroz &gt; liferay-tango - PR#2325 - 2022-03-29[10:33:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/2345/">publish-testray-report#2345</a><br/></div></div>

2022-03-29 17:48 UTC, Luizcarlosqueiroz commented
ci:test:tango

2022-03-29 20:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:tango - 4 out of 11 jobs passed in 1 hour 33 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3070">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1327401_3235</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7977a6ee2fbb54bf93dc9da0cf658f5479470973">7977a6ee2fbb54bf93dc9da0cf658f5479470973</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89ea6114c45e45c60cc945726f5c26108b3e7669">89ea6114c45e45c60cc945726f5c26108b3e7669</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3069">Acceptance Upstream DXP (master) #3069</a></p><details><summary><strong>ci:test:tango - 4 out of 11 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3235/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/42019/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16096/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41309/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28496/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/45288/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16095/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38875/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41308/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/42018/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38874/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3235/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/42019/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>152 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=13/42019//consoleText">AXIS_VARIABLE=13 #42019</a><ol><li><div><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=13/42019//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ContentDashboardWithAC_ViewMetricsButtonKebabWhenBlogHasDPT_">LocalFile.ContentDashboardWithAC#ViewMetricsButtonKebabWhenBlogHasDPT</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/3235/functional-tomcat90-mysql57-jdk8/0/13/LocalFile.ContentDashboardWithAC_ViewMetricsButtonKebabWhenBlogHasDPT/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/3235/functional-tomcat90-mysql57-jdk8/0/13/LocalFile.ContentDashboardWithAC_ViewMetricsButtonKebabWhenBlogHasDPT/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/3235/functional-tomcat90-mysql57-jdk8/0/13/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16096/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>129 Tests Passed.<br/>13 Tests Failed.</p></div><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/16096//consoleText">AXIS_VARIABLE=0 #16096</a><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/16096//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ABTestWithoutACConnection_CheckABTestingClosedAfterLogout_">LocalFile.ABTestWithoutACConnection#CheckABTestingClosedAfterLogout</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/3235/functional-tomcat90-mysql57-jdk8/1/0/LocalFile.ABTestWithoutACConnection_CheckABTestingClosedAfterLogout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/3235/functional-tomcat90-mysql57-jdk8/1/0/LocalFile.ABTestWithoutACConnection_CheckABTestingClosedAfterLogout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/3235/functional-tomcat90-mysql57-jdk8/1/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/16096//consoleText">AXIS_VARIABLE=1 #16096</a><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/16096//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ACSegmentsInDXP_CheckNotEditableSegmentFromACAtDXP_">LocalFile.ACSegmentsInDXP#CheckNotEditableSegmentFromACAtDXP</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/3235/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.ACSegmentsInDXP_CheckNotEditableSegmentFromACAtDXP/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/3235/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.ACSegmentsInDXP_Che [...]

2022-03-29 20:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3235/">test-portal-acceptance-pullrequest(master)#3235</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3235/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>tango<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/2325">liferay-tango#2325</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1650180437">[master] ci:test:tango - Luizcarlosqueiroz &gt; liferay-tango - PR#2325 - 2022-03-29[11:30:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/9409/">publish-testray-report#9409</a><br/></div></div>

2022-03-29 22:11 UTC, Luizcarlosqueiroz commented
@CarlosBrichete

2022-03-30 10:01 UTC, CarlosBrichete requested changes

2022-03-30 10:01 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		task ("Create a Basic Document") {
As this is a priority 4 test, it should be included in the tango-acceptance routine. Please add:
 _property portal.acceptance = "true";_

2022-03-30 12:39 UTC, Luizcarlosqueiroz commented
Hey @CarlosBrichete ! Property added. Should we run the ci tests again?

2022-03-30 12:53 UTC, CarlosBrichete commented
> Hey @CarlosBrichete ! Property added. Should we run the ci tests again?

No, there's no need :)

2022-03-30 12:53 UTC, CarlosBrichete commented
ci:forward

2022-03-30 12:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/1841/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/1841/jenkins-report.html">here</a>.</b></p>

2022-03-30 12:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4c313fa9b06e385f60557d5d1130e76eb7ee70c7">4c313fa9b06e385f60557d5d1130e76eb7ee70c7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/tree/LPS-150510-Bug-Automation">LPS-150510-Bug-Automation</a><br/>Branch GIT ID: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/commit/7e8618f38fe76982dec55004347f898bd8cac766">7e8618f38fe76982dec55004347f898bd8cac766</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/1841/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/1841/jenkins-report.html">here</a>.</h5></details></html>

2022-03-30 12:58 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/1841//consoleFull)

2022-03-30 12:58 UTC, liferay-continuous-integration commented
Unexpected errors occurred while attempting to forward pull request to 'brianchandotcom', please try again later or contact a CI Infrastructure member for assistance.
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/1841//consoleFull)

2022-03-30 12:59 UTC, liferay-continuous-integration commented
Unexpected errors occurred while attempting to forward pull request to 'brianchandotcom', please try again later or contact a CI Infrastructure member for assistance.
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/1841//consoleFull)

2022-03-30 13:00 UTC, CarlosBrichete approved these changes

2022-03-30 13:00 UTC, CarlosBrichete commented
ci:forward

2022-03-30 13:00 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-03-30 13:00 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-03-30 13:01 UTC, liferay-continuous-integration commented
Unexpected errors occurred while attempting to forward pull request to 'brianchandotcom', please try again later or contact a CI Infrastructure member for assistance.
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/1841//consoleFull)

2022-03-30 13:02 UTC, liferay-continuous-integration commented
Unexpected errors occurred while attempting to forward pull request to 'brianchandotcom', please try again later or contact a CI Infrastructure member for assistance.
[Console](https://test-1-25.liferay.com/job/forward-pullrequest/316//consoleFull)

2022-03-30 13:02 UTC, liferay-continuous-integration commented
Unexpected errors occurred while attempting to forward pull request to 'brianchandotcom', please try again later or contact a CI Infrastructure member for assistance.
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/1841//consoleFull)

2022-03-30 13:02 UTC, liferay-continuous-integration commented
Error has occurred while forwarding pull request to `brianchandotcom`
See console log for details: [Full Console](https://test-1-26.liferay.com/job/test-portal-source-format/1841/consoleText)

2022-03-30 13:03 UTC, liferay-continuous-integration commented
Unexpected errors occurred while attempting to forward pull request to 'brianchandotcom', please try again later or contact a CI Infrastructure member for assistance.
[Console](https://test-1-25.liferay.com/job/forward-pullrequest/316//consoleFull)

2022-03-30 13:04 UTC, closed without merging

2022-03-30 13:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/1841/">test-portal-source-format#1841</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/1841/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/2325">liferay-tango#2325</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1651175815">[master] ci:test:sf - Luizcarlosqueiroz &gt; liferay-tango - PR#2325 - 2022-03-30[05:54:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/6782/">publish-testray-report#6782</a><br/></div></div>

2022-03-30 13:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1163/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1163/jenkins-report.html">here</a>.</b></p>

2022-03-30 13:27 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1163//consoleFull)

2022-03-30 13:27 UTC, liferay-continuous-integration commented
Closed pull request will not be forwarded.