LPS-127289
liferay-tango/liferay-portal pull request #3024
Opened 2022-11-14 13:27 UTC by Mikellorza

2022-11-14 13:27 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-11-14 13:54 UTC, cgoncas requested changes
This PR doesn't include any tests :(.

Also we use OData expressions, so we should not use regext to change these expressions.

2022-11-14 14:13 UTC, Mikellorza commented
Hi @cgoncas ,

Yes I have to create some test for this bug but for now we can review the solution and if it is fine I can add some test for this bug :)

Thanks

2023-03-23 08:49 UTC, Mikellorza commented
ci:close

2023-03-23 08:49 UTC, closed without merging