LPS-169312
liferay-tango/liferay-portal pull request #3213
Opened 2023-02-02 17:53 UTC by rafaellajordao

2023-02-02 17:53 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-02-07 17:25 UTC, rafaellajordao commented
ci:test:sf

2023-02-07 18:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-source-format/5797/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5797/jenkins-report.html">here</a>.</b></p>

2023-02-07 18:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>tango</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/6216/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6216/jenkins-report.html">here</a>.</b></p>

2023-02-07 18:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6005c85e2ecc68aa2d02852902b1c6794ad83fad">6005c85e2ecc68aa2d02852902b1c6794ad83fad</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-169312">LPS-169312</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/e1348c859920fce831db4e6a118c48f8a34628ca">e1348c859920fce831db4e6a118c48f8a34628ca</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-source-format/5797/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5797/jenkins-report.html">here</a>.</h5></details></html>

2023-02-07 20:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-4.liferay.com/job/test-portal-source-format/5797/">test-portal-source-format#5797</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5797/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/3213">liferay-tango#3213</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2188676334">[master] ci:test:sf - rafaellajordao &gt; liferay-tango - PR#3213 - 2023-02-07[10:53:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-4.liferay.com/job/publish-testray-report/3735/">publish-testray-report#3735</a><br/></div></div>

2023-02-07 21:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/6216/">test-portal-acceptance-pullrequest(master)#6216</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6216/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>tango<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/3213">liferay-tango#3213</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2188747041">[master] ci:test:tango - rafaellajordao &gt; liferay-tango - PR#3213 - 2023-02-07[10:56:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/13656/">publish-testray-report#13656</a><br/></div></div>

2023-02-08 15:50 UTC, CarlosBrichete requested changes

2023-02-08 15:50 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/Collections.testcase
> +		property portal.acceptance = "true";
This test has priority 3 so it is not considered as acceptance. Remove this property.

2023-02-08 15:50 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/Collections.testcase
> +		property portal.acceptance = "true";
This test has priority 3 so it is not considered as acceptance. Remove this property.

2023-02-08 15:50 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/Collections.testcase
> +		property portal.acceptance = "true";
This test has priority 3 so it is not considered as acceptance. Remove this property.

2023-02-08 15:50 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/Collections.testcase
> +		property portal.acceptance = "true";
This test has priority 3 so it is not considered as acceptance. Remove this property.

2023-02-08 15:50 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/Collections.testcase
> +		property portal.acceptance = "true";
This test has priority 3 so it is not considered as acceptance. Remove this property.

2023-02-08 15:50 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/Collections.testcase
> +		property portal.acceptance = "true";
This test has priority 3 so it is not considered as acceptance. Remove this property.

2023-02-08 17:24 UTC, rafaellajordao commented
ci:forward

2023-02-08 17:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/4763/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4763/jenkins-report.html">here</a>.</b></p>

2023-02-08 17:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d8769dbc1d0dc79fc8ed0957b685e3c0be9e265a">d8769dbc1d0dc79fc8ed0957b685e3c0be9e265a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-169312">LPS-169312</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/d27feb6cf6374c4309801665dbd3930ad1550778">d27feb6cf6374c4309801665dbd3930ad1550778</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4763/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4763/jenkins-report.html">here</a>.</h5></details></html>

2023-02-08 17:28 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/4763//consoleFull)

2023-02-08 17:28 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/129932
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/4763//consoleFull)

2023-02-08 17:28 UTC, closed without merging

2023-02-08 18:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/7542/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7542/jenkins-report.html">here</a>.</b></p>

2023-02-08 18:21 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/129932

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/7542//consoleFull)

2023-02-08 18:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/7542/">test-portal-acceptance-pullrequest(master)#7542</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7542/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-tango/liferay-portal/pull/3213">liferay-tango#3213</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2189880508">[master] ci:test:relevant - rafaellajordao &gt; liferay-tango - PR#3213 - 2023-02-08[10:17:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/18022/">publish-testray-report#18022</a><br/></div></div>